nats-io/nats.rs

CHANGELOG.md, README.md, examples/nats-box/main.rs, src/lib.rs
In the lead-up to implementing reconnection logic, it's important to reduce some complexity where possible to reduce the friction of introducing changes over time. I started diving into reconnection, but found myself getting a bit confused with the various typestates relating to connectivity etc... and only later did I realize they were only really being used at initialization time.
This separates concerns a bit by splitting the complex typestate into different objects that do different things: 
* `Options` which are now a publicly documented type that can be operated on in the same way that Connection could be before when it had the complex typestate. 
* `Connection` now doesn't have any complex typestate, and all access to its state has been simplified by allow it to avoid referring to …
=> Separate complex initialization-only typestate from Connection

src/lib.rs
We can rely on the default implementation for the same functionality as the provided functions to serde.
=> small cleanups

src/lib.rs, src/parser.rs, src/shared_state.rs, src/subscription.rs
The `SharedState` object is where I'm putting the various reconnection-related parameters. With ad-hoc `Arc`s used in different places in more fine-grained ways it's easy to cause cycles and violate assumptions about lifetimes. Now there's just one type behind a single `Arc`, simplifying the dependency graph and reducing arc-related overhead (no need to clone and store multiple `Arc`s).
=> Refactor shared state behind a single Arc to simplify the dependency graph

Cargo.toml, src/inbound.rs, src/lib.rs, src/outbound.rs, src/parser.rs, src/shared_state.rs, src/tls.rs, tests/reconnection.rs
=> TLS Support. Closes #5.

tests/reconnection.rs
After #21, the reconnection test will fail due to not being able to establish a connection to the intentionally-bad server initially.
This has the test retry connection initially, to account for the new initial connection semantics.
cc @derekcollison
=> retry initial connection in now occasionally-failing reconnect test

.travis.yml, CHANGELOG.md, Cargo.toml, README.md, src/lib.rs, src/outbound.rs, src/tls.rs
Version 0.3.1 caused breakage for users of Rust with a compiler version 1.41 or earlier, due to the usage of the `matches!` macro which stabilized in Rust `1.41.0`. This patch does two things:
* lowers MSRV to 1.37.0
* makes our MSRV explicit
I am going to publish 0.3.2 and "yank" 0.3.1 to prevent breakage for users.
=> Lower minimum supported Rust version to 1.37.0 and release 0.3.2 

src/lib.rs
@derekcollison  does it make sense to allow users to get a clone the ServerInfo directly?
=> Expose the client_id provided by the most recently connected server

src/inbound.rs, src/lib.rs, src/outbound.rs
I've also implemented flush_timeout to have parity with the Go client.
=> Add support for RTT calculation, as well as flush_timeout

src/lib.rs
It turns out that `shared_state` and `reply` fields in `Message` are always either both `Some` or both `None`.
In theory, it'd be great if those were a part of the same `Option`, something ilke:
```rust
reply: Option<(String, Arc<SharedState>)>,
```
However, field `reply` is already public with the `Option<String>` type so changing this would be a breaking change.
I restructured the `respond()` function to be a bit more indicative of this invariant and to fail fast if we break it.
=> Refactor Message::respond()

src/inbound.rs, src/lib.rs
Just realized this bug exists while scanning the source code
Bug:
* client is disconnected
* client calls `Connection::flush`
* a `crossbeam_channel::Sender` is pushed into the pongs `VecDeque`
* `Outbound::send_ping` is called, which returns `Err(NotConnected)`
* the client early-exits from `Connection::flush`
* client reconnects
* client calls `Connection::flush` again, adds new `Sender` to pong queue, sends PING to server
* server sends back PONG
* `Inbound` receives and parses the PONG, pops the first `Sender` from the pong queue (which is no longer waiting)
* the second client call hangs on the crossbeam_channel's Receiver until the receive timeout fires, when it should have actually received a success.
We need to hold the pong queue mutex across the call to send_ping (which may …
=> Address bug with PONG receiver leaks during disconnection

src/lib.rs
Now the client version number will always be correct.
=> Fix the hardcoded client version

Cargo.toml, src/connect.rs, src/creds_utils.rs, src/lib.rs, src/parser.rs, src/secure_wipe.rs, src/shared_state.rs
This PR adds `ConnectionOptions::with_credentials()` that allows you to specify a `.cred` file to authenticate.
Connection options handling is becoming unwieldy - would you be okay with me doing a little bit refactoring around that? In particular, I'd like to move everything options-related into a dedicated file.
=> Add authentication with credentials file

src/connect.rs, src/inbound.rs, src/lib.rs, src/outbound.rs, src/secure_wipe.rs, src/shared_state.rs, tests/reconnection.rs
* fix several IO error handling issues where the outbound connect buffer was not transitioned to the Disconnected state immediately after encountering an error while sending data to the server, resulting in garbled commands being sent to the server after other IO errors were encountered
* have the reconnect test send far more PINGs to stress out the client more
* have the bad test server properly assert that commands end with the expected number of words
=> further lock down io error handling

examples/nats_bench.rs
small bugfix in the new benchmarking tool. `char` is 4 bytes, and `String` uses 1-4 bytes per char. this uses a normal `Vec<u8>` to make it similar to the go bench. @stjepang caught this while using it.
=> Use raw bytes instead of utf-8 chars in the nats_bench program

src/shared_state.rs, src/subscription.rs
Now that performance is becoming a subject of conversation, this will surface information to profilers to improve output
(screenshot from using [hotspot](https://github.com/KDAB/hotspot) w/ data generated from [cargo flamegraph](https://github.com/flamegraph-rs/flamegraph) with the command `cargo flamegraph --example nats_bench -- test -n 10000000` using the new bench tool.
=> Name all threads created for normal system operation

src/lib.rs
I'd like to be able to clone() this type as I've refactored out previous usage of natsclient in a project which derived clone on message. It makes it easier to clone the message to be passed around to multiple threads
=> Derive Clone for Message

src/asynk/client.rs, src/asynk/connection.rs
With the latest client rewrite we reintroduced the annoying issue where the client keeps reconnecting if the initial connect has failed. We should fail fast because `Options` were most likely misconfigured and the connection will never be established.
The guts of `Client::connect()` are kind of gross right now, and that is partly due to the way smol is currently designed. We *must* spawn a thread running `smol::run()`, or else `Async` and `Timer` do not work. This is because `smol::run()` "drives" the I/O reactor. The next version of smol (soon to be released) will create an I/O reactor thread on its own so this will become much cleaner and we'll be able to begin connecting without spawning the client thread. I'll simplify the code, I promise!
=> Don't keep reconnecting if the initial connect fails

nats_test_server/Cargo.toml, nats_test_server/src/bin/nats_test_server.rs, nats_test_server/src/lib.rs
this lets anyone run `cargo install nats_test_server` and get this server to test their clients against, similarly to how we tested things while writing the rust client
=> reusable fault injection server binary

examples/nats-box/main.rs
Just a small improvement to nats-box. It's really useful on embedded devices. Thank you.
=> Add auth-token flag. Group auth-token and certs into auth clap::ArgGroup

Cargo.toml, src/asynk/client.rs, src/asynk/subscription.rs, src/subscription.rs
Previously, `Subscription::unsubscribe()` and `Subscription::close()` were doing nothing. This PR adds the missing logic - the subscription gets recorded in the `unsubscribed` set denoting dead subscriptions for which we haven't sent UNSUB yet. Eventually, `cleanup_subscriptions()` will be called that collects dead subscriptions and sends UNSUB to the server.
Closes #82
=> Fix unsubscription

CRATE.md, README.md, src/asynk/mod.rs, src/lib.rs, src/options.rs
This PR finally exposes the long-awaited async interface for the NATS client. :)
Will publish a new version of the crate when this PR gets merged.
=> Make the asynk module public

src/asynk/client.rs
Fix mutex usage for https://github.com/nats-io/nats.rs/issues/92 
MutexGuard for unsubscribed list was captured by for loop context.
=> Fix Mutex usage in asynk::client::cleanup_subscriptions function.

Cargo.toml, src/asynk/client.rs, src/lib.rs, src/subscription.rs
We're not using `crossbeam-channel` anywhere, and yet there were some remnants of it our public API. I'm removing those and also removing `const` annotations on some functions that are not really useful (they may only be useful on *constructors*, perhaps).
I'm planning to further clean up the API after the next release.
=> Remove crossbeam-channel from the public API

src/asynk/client.rs, src/asynk/connection.rs
This problem was reported by @dontlaugh on Slack (#rust channel),
The issue is that dropping `Connection` does not trigger thread shutdown, so if you drop it without calling `.close().await` on it, the thread simply keeps running and therefore keeps holding an active NATS connection.
The solution is to signal to the thread that it must shutdown when `Connection` is dropped.
=> Fix connection leak

src/asynk/client.rs, src/lib.rs, tests/drop.rs
Discussed this with @derekcollison - I'm proposing a simple solution here. Changes:
1. When `nats::Connection` is dropped, we flush (and wait for the flush to complete).
2. When `nats::asynk::Connection` is dropped, we let the client thread asynchronously flush (but we don't wait for it).
cc @andrewbanchich
=> Flush before dropping the connection

CHANGELOG.md, Cargo.toml
fixes issue when using the regex crate to process creds:
```
Running `target/release/ngs-usage-server-rs`
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
\s*(?:(?:[-]{3,}.*[-]{3,}\r?\n)([\w\-.=]+)(?:\r?\n[-]{3,}.*[-]{3,}\r?\n))
^^
error: Unicode-aware Perl class not found (make sure the unicode-perl feature is enabled)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
)', /home/t/.cargo/registry/src/github.com-1ecc6299db9ec823/nats-0.8.3/src/auth_utils.rs:67:10
stack backtrace:
0: rust_begin_unwind
at /rustc/1773f60ea5d42e86b8fdf78d2fc5221ead222bc1/library/std/src/panicking.rs:495:5
1: core::panicking::panic_fmt
at …
```
=> Fix regex usage by enabling the unicode-perl feature.

Cargo.toml, examples/nats_bench.rs
cc @derekcollison 
```
λ cargo run --example=nats_bench --release -- test --number-of-messages=100000000
Finished release [optimized] target(s) in 0.05s
Running `target/release/examples/nats_bench test --number-of-messages=100000000`
Starting benchmark [msgs=100000000, msgsize=128, pubs=1, subs=0]
duration: 18.103644136s frequency: 5523946 mbps: 690
latency breakdown in microseconds:
min:         65 ns
50th percentile:         94 ns
75th percentile:         95 ns
90th percentile:        100 ns
95th percentile:        108 ns
97.5th percentile:        115 ns
99th percentile:        127 ns
99.99th percentile:      26369 ns
99.999th percentile:      34543 ns
max:     830679 ns
```
(above numbers targeting a local 2.1.6 nats server)
=> Add latency breakdown for nats_bech test

Cargo.toml, async-nats/Cargo.toml, async-nats/examples/async_nats_bench.rs, async-nats/src/lib.rs, src/client.rs, src/lib.rs, src/message.rs
The NATS client offers two kinds of APIs: blocking and asynchronous. The latest version of `nats` published on crates.io has an implementation written in async style, and the blocking API simply wraps the async API with `block_on(...)` calls.
We experienced difficulties maintaining that codebase due to instability of async Rust, general friction of writing code in async style, and hidden performance costs. Then we removed async code from the guts of the client. The current master branch contains a client written in good old sync style with a blocking API. However, the async API is missing.
This PR brings the async API back, which is now just a wrapper around the sync API. We use `unblock(...)` from the `blocking` crate to make functions asynchronous. Note that `unblock()` "cheats" by …
=> Add async-nats crate

README.md
The README claims that the sync interface is a thin wrapper around the async interface, but as far as I can tell the inverse is true.
=> Fix typo in README: async is a wrapper around sync

src/proto.rs
`to_uppercase()` is more expensive than `to_ascii_uppercase()` because it handles UTF-8 characters and needs to do costly lookups in the table mapping lowercase characters to uppercase characters.
Also, there is no point in uppercasing the whole line of text - we're only interested in the first word.
Fixes #139
cc @tekjar
=> Optimize to_uppercase()

nats_test_server/Cargo.toml, nats_test_server/README.md, nats_test_server/src/lib.rs
The test server now maintains separate subscriptions for different clients and forwards messages based on those.
I've also changed the ping timeout in the server from 50 micros to 50 millis
=> Add support for multiple clients in test server

src/connect.rs
Just a really silly bug... The "echo" option was specified only when set to true, but it should've been specified when it's false because true is the default. Now we always specify it in the NATS protocol.
Fixes #147
=> Fix the no_echo setting

CHANGELOG.md, Cargo.toml, async-nats/Cargo.toml, src/jetstream.rs, tests/jetstream.rs
Fixes two JetStream related bugs:
- #164 `Consumer::process_timeout` properly times out
from all branches.
- #164 `Consumer::pull_opt` now properly checks the
`Consumer.deliver_subject`.
=> Cut 0.9.9. Closes #163.

src/subscription.rs
Gives access to the a crossbeam Receiver in the Subscription struct. Useful for [crossbeam_channel::select][0] macro. Diff should speak for itself. I didn't find a way to select on multiple Subscriptions in one thread without access to the crossbeam channel. Is there a better way? 
Offtopic: I used the async-nats with tokio at first, but I think [async_nats::Subsciption::next][1] implementation will lose messages if canceled by [tokio::select][2].
[0]: https://docs.rs/crossbeam-channel/0.5.0/crossbeam_channel/macro.select.html
[1]: https://github.com/nats-io/nats.rs/blob/master/async-nats/src/lib.rs#L285
[2]: https://docs.rs/tokio/0.2.18/tokio/macro.select.html
=> Give access to Subscription's crossbeam channel

src/headers.rs
=> Don't split a header into more than two parts

Cargo.toml
context: https://jakedeichert.com/blog/reducing-rust-incremental-compilation-times-on-macos-by-70-percent/
=> Use unpacked split-debuginfo for speeding up macos builds of the crate.

.github/workflows/test.yml, CHANGELOG.md, Cargo.toml, async-nats/Cargo.toml, src/client.rs, src/lib.rs
* add CI test to ensure examples always compile
* fix future incompatibility issue while using the log macro in a match arm
* avoid using a result in a return type for infallibly closing a connection
=> A few small cleanups, including a compilation fix for a future-incompatible example

CHANGELOG.md, Cargo.toml, async-nats/Cargo.toml, async-nats/src/lib.rs
- Add support for request_timeout in async nats
Why: 
- If we get disconnected from NATS for reason, as the lib use unblock() under the hood, the application will leak threads waiting for the operation to receive a reply that will never comeback.
- Even if we get back the connection to NATS, those threads are lost in the limbo as they will never be able to receive a reply
- Wrapping `async request` within a futures::timeout, works but does not kill the underlying threads used by unblock
What:
- The PR exposes the `request_timeout` function in async-nats
=> Add async request_timeout

CHANGELOG.md, Cargo.toml, async-nats/Cargo.toml, examples/nats_bench.rs, src/client.rs, src/jetstream.rs, src/lib.rs
This is the real fix for the issue encountered in benchmarks where subscriptions would cause lock-ups due to slow consumers.
This comes with the introduction of a mandatory locking protocol which must always be followed to avoid deadlocks going forward. But this is important for allowing reads and writes to make progress independently of each other, and the situations that require both locks to be held are pretty infrequent.
=> Use fine-grained locking on read and write-related state

async-nats/src/lib.rs
documents the requirement to manually await `async_nats::Subscription::unsubscribe` due to Rust's lack of `AsyncDrop`, mentioned in https://github.com/nats-io/nats.rs/issues/179#issuecomment-843987681
=> Doc-only update of async_nats::Subscription

.github/workflows/test.yml
Switches the toolchain from nightly to stable to avoid any unexpected surprises.
=> Use stable toolchain for clippy checks

.github/workflows/test.yml, README.md
This bumpos the minimum supported rust version to 1.52.0 which is required for `str::split_once`.
=> Bump MSRV to 1.52.0

src/jetstream.rs, src/lib.rs, src/options.rs, tests/jetstream.rs, tests/util/mod.rs
First pass at separating JetStream from `Connection`.
- Moves JetStreamOptions into the `jetstream` module.
- Introduces a `jetstream::JetStream` type that will be the home of `publish` with acks and other ops ala the Go and JavaScript clients.
- Adds a short-hand for instantiating these `JetStream` contexts via `nats::jetstream::new(nc)`.
Was considering `jetstream::Connection`, `jetstream::Client` and `jetstream::Context` and in the end just went with `jetstream::JetStream` but is bike-shreddable.
Easiest to review on a commit by commit basis.
=> Introduce a `JetStream` type

src/headers.rs, src/jetstream.rs, src/jetstream_types.rs, src/lib.rs, tests/jetstream.rs
This adds adds support for `JetStream` publishing.
A few tangental fixes were made along the way.
Supercedes #218 
Closes #215
=> Add support for JetStream publishing

tests/configs/jetstream.conf, tests/util/mod.rs
Quotes were resulting in a directory named `./$SD` directory to be created and used on Unix for storage, which leads to racing between the tests and frequent failures.
This makes use of the `--store_dir` cli option instead.
=> Use temporary directories for storage

.github/workflows/test.yml
- Remove jetstream job
- Don't use rustup to re-install clippy
- Normalises jobs and step naming splitting them into two groups: tests and checks.
=> Workflow improvements

src/asynk.rs, src/client.rs, src/header.rs, src/jetstream.rs, src/lib.rs, src/message.rs, src/proto.rs
This makes the header module public which contains the header map type and constants for various known headers (taking a little inspiration from the [http crate](https://docs.rs/http/0.2.5/http/header/index.html) here).
The top level `Headers` type still exists, but has been aliased to the new name and the alias is marked as deprecated.
=> Add header module

src/client.rs, src/connect.rs, src/connector.rs, src/lib.rs, src/options.rs, tests/duck_mode.rs, tests/lame_duck_mode.rs, tests/util/mod.rs
Realized that we should probably do more when new info arrives, hence used `process_info` instead of more specific name for lame duck tape mode.
=> Lame duck mode support

.github/workflows/test.yml, Cargo.toml, README.md, src/client.rs, src/header.rs, src/jetstream.rs, src/jetstream_push_subscription.rs, src/jetstream_types.rs, src/lib.rs, src/message.rs, tests/jetstream.rs
Adds support for jetstream subscriptions as described by ADR-15 and ordered consumers as described by ADR-17.
There's one defect from ADR-15 as it is right now:
> If no message or status is received within a certain time period, an alarm should be surfaced to the user in a way that makes sense in the client language, for example by notifying the user through the asynchronous error callback.
=> Re-work JetStream consumer interface

src/lib.rs
Currently the `Handler` struct returned from `Subscription#with_handler` is public but not exported as part of the library. This exports it so the handler can be used as a return type etc.
=> fix: publicly export handler struct

src/asynk.rs, src/client.rs, src/options.rs
We have had issues connecting on the first attempt, similar to issue brought up in the past:
https://github.com/nats-io/nats.rs/issues/99
We modified the nats.rs to enable us to enter the retry loop on the first connection attempt.  Our application behavior is such that we do not require the NatsServer be up and running when we start.  This change allows for that behavior.
=> Proposed update to enable reconnect on first attempt

tests/lame_duck_mode.rs, tests/util/mod.rs
Lame duck mode tests were sometimes failing because of the fact that they were not targeting specific PID.
With each test in parallel, risk of race happening was increasing.
This allows func that calls lame_duck_mode to refer specific PID.
=> Fix lame duck mode tests race

examples/nats-box/main.rs, src/asynk.rs, src/client.rs, src/connector.rs, src/lib.rs, src/options.rs, tests/drop.rs
The main change of the PR is turning `fn connect(&str)` into `fn connect<I: IntoServerList>(nats_url: I)`. The reason is to make it more prominent which kind of URLs are expected.
The refactoring in the background also cleans-up some code and makes some decisions more explicit like interpreting a missing scheme as `nats://` or the default port `4222`.
This is the implementation as I initially thought of in #216.
=> Introduce ServerAddress

LICENSE, src/asynk.rs, src/auth_utils.rs, src/client.rs, src/connect.rs, src/connector.rs, src/fault_injection.rs, src/header.rs, src/jetstream/mod.rs, src/jetstream/push_subscription.rs, src/jetstream/types.rs, src/kv.rs, src/lib.rs, src/message.rs, src/object_store.rs, src/options.rs, src/proto.rs, src/secure_wipe.rs, src/subscription.rs, tests/async_errors.rs, tests/auth_nkey.rs, tests/auth_tls.rs, tests/auth_user_pass.rs, tests/drop.rs, tests/jetstream.rs, tests/kv.rs, tests/lame_duck_mode.rs, tests/no_responders.rs, tests/reconnection.rs, tests/util/mod.rs
The current license doesn't show up on repo list.
Updated to fix that and also have it in line with other NATS.io repos.
=> Fix License

nats_test_server/src/lib.rs
Subject matching function in test server was only taking into account the number of tokens in message subject.
This caused false matches when a message's subject was a prefix of longer subscription pattern
=> Test server subject matching bug fix

src/client.rs
=> Join all connect threads while closing connection

src/jetstream/mod.rs, src/jetstream/pull_subscription.rs
A few types like `nats::jetstream::push_subscription::Handler` were voldemort types.
This exports the `push_subscription` and `pull_subscription` modules to
avoid that scenario.
=> Export subscription modules

src/header.rs, src/jetstream/mod.rs, src/kv.rs, src/lib.rs, src/message.rs, src/object_store.rs, tests/jetstream.rs
This adds an actual API for headers instead of exposing `inner` publicly.
This is a breaking change.
=> Add a public convenience interface to header maps

src/jetstream/mod.rs, tests/jetstream.rs
Sequence mismatch was checked always for push consumers.
That caused recreating consumers.
Now it does that only for ordered consumers.
=> Check sequence mismatch only for ordered consumer

CHANGELOG.md, Cargo.toml
A patch release fixing long durations until `close()` returned. It was introduced in the graceful shutdown of client connection threads in v0.18.0.
Dropping NATS connection was not affected.
=> Release v0.18.1

Cargo.toml
This is necessary as `0.3.0` was depending on `rand = "0"` thus it is possible for it to switch back to `0.7` or older, which just happened with `nuid` coming in transitively from our dependency on nats. The only change between `nuid 0.3.0` and `0.3.1` is the refinement of the `rand` version constraint. So I bet this is safe.
=> Bump nuid dependency to `0.3.1`

src/lib.rs
I was confused about the difference between `async-nats` and `asynk` but eventually came across #192. Hopefully this will help clarify things for new users.
=> Link to asynk module instead of async-nats

.github/workflows/test.yml, nats/src/jetstream/pull_subscription.rs, nats/src/subscription.rs
This is a workaround until we find reason why few test fails
with the new version of the server.
Also fixes doc examples that were relying on `demo.nats.io` having streams with messages.
=> Bind to nats-server 2.7.4 and fixed deadlocked tests

.github/workflows/test.yml, nats/tests/jetstream.rs
This assertion failure was caused by the fact, that nats-server got all acks and info altogether, and since 2.8.0 changes around acks, this caused info not having acks processed yet. Flushing before requesting info solves the problem.
=> Fix tests failing with nats-server 2.8.0

.github/workflows/test.yml
We run doctests in an isolated task, should be fine to grab port 4222 and run a local server on that redirecting demo.nats.io to it.
=> Use local server for documentation tests

async-nats/examples/sub.rs, async-nats/src/lib.rs, async-nats/tests/client_tests.rs
add queue subscription and unit test
there are a couple open questions on function naming (see TODO in code)
Signed-off-by: Steve <steve@cosmonic.com>
=> add queue subscriber and unit test

async-nats/src/lib.rs
This reverts commit dfde8c26528b8f839f683e96825998d0cc1a920d.
=> Revert "Avoid vec allocation when parsing message ops"

async-nats/Cargo.toml, async-nats/src/header.rs, async-nats/src/lib.rs, async-nats/tests/client_tests.rs
Header support for incoming and outgoing messages.
This time we're re-using the header types from the http crate.
=> Support sending and receiving messages with headers

async-nats/examples/pub.rs, async-nats/src/connection.rs, async-nats/src/lib.rs, async-nats/tests/client_tests.rs, async-nats/tests/nats_server/mod.rs, nats/examples/nats-box/main.rs, nats/examples/nats_bench.rs, nats/examples/serde-json/main.rs, nats/tests/util/mod.rs
Fixed all linter warnings reported with:
```
cargo clippy --examples --tests --all-features -- --deny clippy::all 
```
=> Fix all clippy warnings

async-nats/src/connection.rs, async-nats/src/lib.rs
This inlines Command::TryFlush in the command handler, rather than doing it during operation encoding.
=> Handle `TryFlush` as a command

async-nats/examples/pub.rs, async-nats/examples/sub.rs, async-nats/src/lib.rs, async-nats/tests/client_tests.rs
Supersedes https://github.com/nats-io/nats.rs/pull/421
=> `Client` doesn't need to be mutable self

.gitignore, nats/src/jetstream/pull_subscription.rs, nats/src/jetstream/push_subscription.rs, nats/src/kv.rs
Fixes the issue mentioned [here](https://github.com/nats-io/nats.rs/issues/446#issue-1242024070)
=> remove recursive calls

async-nats/src/lib.rs
If a subscriber is dropped during reconnect, it likely it never fired the unsubscribe command. But we know it closed so we can just not ever re-create the subscription.
=> Only retain non-closed subscriptions on reconnect

async-nats/src/connection.rs, async-nats/src/lib.rs
We should flush when dealing with commands, rather than in the writer.
=> Do not flush in write calls

.github/workflows/test.yml
Adds a concurrency group to prevent force pushes and similar events on the same pull request to fill up the backlog for hours (benchmark takes quite some time once it starts filling up).
=> Use a concurrency group to prevent action backlog

async-nats/src/jetstream/context.rs, async-nats/tests/jetstream_tests.rs
The two paths of get_or_create_stream returns different types, which is fairly unexpected.
This changes `jetstream::Context::create_stream` to return a `Stream`. If we need a non-binding variant we can add `insert_stream` which returns `stream::Info` rather than `Stream`.
=> Make `jetstream::Context::create_stream` return `Stream`

async-nats/src/lib.rs, async-nats/tests/client_tests.rs
After some back and forth with @Jarema , I was having some trouble connecting to `connect.ngs.global` with the nats client. I was getting an error for `UnsupportedNameType`, which I tracked down in [rustls](https://github.com/rustls/rustls/blob/main/rustls/src/verify.rs#L330). When I took a look at this function, it seems that attempting to connect to NGS always resulted in the `info.host` variable filled in as an IP address, which as you can see in the above function creates an error.
Simply removing this fixes the issue _for me_ but I wanted to open this PR for discussion. I'm not entirely sure if connecting to an IP address with TLS is a totally valid use case, or if ignoring the `info.host` value here is the proper solution. What also worked for me is reordering the connections to try …
=> Removed attempt to connect to server info host when TLS is enabled

async-nats/src/jetstream/consumer/pull.rs, async-nats/src/jetstream/mod.rs, async-nats/tests/jetstream_tests.rs
Alternative names include but are not limited to series, serial, linear, etc.
=> Rename `Process` stream to `Sequence`

nats-server/src/lib.rs, nats/src/connector.rs, nats/tests/auth_token.rs, nats/tests/configs/token_auth.conf
Many NATS clients allow for token authentication to be specified in a connection URL by passing a username without a password. This enables that approach, and adds some tests.
If this looks good, I'm happy to make a similar change on the `async_nats` side, either in this PR or in a follow-up as appropriate.
=> Allow tokens in connection strings and add tests

async-nats/src/jetstream/consumer/mod.rs, async-nats/src/jetstream/context.rs, async-nats/src/jetstream/mod.rs, async-nats/src/jetstream/stream.rs
For consistency without trailing colon ala std lib as it is rendered with a heading tag in rustdoc.
=> Normalize the examples heading

async-nats/src/jetstream/account.rs, async-nats/src/jetstream/context.rs, async-nats/src/jetstream/mod.rs, async-nats/tests/jetstream_tests.rs
See https://github.com/nats-io/nats-architecture-and-design/issues/120
=> Add `query_account` to `jetstream::Context`

async-nats/src/lib.rs
Normalizes the introduction example, making use of try operators instead of unwrap.
=> Normalize introduction example

nats/src/lib.rs
Hi. I've been going through the code as I've been looking to contribute and I noticed the wrong function being used in one of the doc tests.
=> Use correct flush_timeout operation in doc test

async-nats/Cargo.toml, async-nats/src/tls.rs
This PR switches webpki that is using MPL license to rustls-native-certs.
Changes in behaviour: https://github.com/rustls/rustls-native-certs#should-i-use-this-or-webpki-roots
resolves #552
=> Switch webpki to rustls-native-certs

async-nats/CHANGELOG.md, async-nats/Cargo.toml, nats/CHANGELOG.md, nats/Cargo.toml
This release features a lot of improvements and additions to `JetStream` API and adds `Push Consumer`.
* Add `query_account` to `jetstream::Context` by @caspervonb in https://github.com/nats-io/nats.rs/pull/528
* Add streams to push consumers by @caspervonb in https://github.com/nats-io/nats.rs/pull/527
* Add no_echo option by @Jarema in https://github.com/nats-io/nats.rs/pull/560
* Add `jetstream::Stream::get_raw_message` by @caspervonb in https://github.com/nats-io/nats.rs/pull/484
* Add Pull Consumer builder by @Jarema in https://github.com/nats-io/nats.rs/pull/541
* Allow unknown directives to be skipped when parsing by @caspervonb in https://github.com/nats-io/nats.rs/pull/514
* Narrow error type returned from client publishing by @caspervonb in …
=> Release async-nats/v0.16.0 & nats/v0.22.0

async-nats/src/jetstream/consumer/mod.rs, async-nats/src/jetstream/message.rs, async-nats/src/jetstream/response.rs, async-nats/src/message.rs, async-nats/src/options.rs, async-nats/src/status.rs
=> Add missing module docs headers

.github/workflows/test.yml
We don't make much use of this in async, takes up runner time.
=> Remove fault injection run from workflow

nats/src/jetstream/types.rs
Add cluster information on ConsumerInfo && StreamInfo,
Follow the structure of ```nats``` CLI Tool within ```trace``` Mode.
- Jetstream Stream API Trace
> nats str report --trace
```
{"type":"io.nats.jetstream.api.v1.stream_list_response","total":1,"offset":0,"limit":256,"streams":[{"config":{"name":"test","subjects":["test"],"retention":"limits","max_consumers":-1,"max_msgs":-1,"max_bytes":-1,"max_age":0,"max_msgs_per_subject":-1,"max_msg_size":-1,"discard":"old","storage":"file","num_replicas":3,"duplicate_window":120000000000,"sealed":false,"deny_delete":false,"deny_purge":false,"allow_rollup_hdrs":false},"created":"2022-06-24T11:04:21.564710722Z","state":{"messages":10,"bytes":531,"first_seq":1,"first_ts":"2022-06-24T11:04:36.593164161Z","last_seq":10,"last_ts":"2022-06-24T11:04:36.599 …
```
=> Add cluster to streaminfo/consumerinfo struct

async-nats/src/jetstream/consumer/mod.rs, async-nats/src/jetstream/consumer/pull.rs, async-nats/src/jetstream/consumer/push.rs
Unnecessary cluster info found. Removed.
=> Remove ClusterInfo from Config

async-nats/src/jetstream/consumer/push.rs, async-nats/tests/jetstream_tests.rs
We didn't account properly for stream/consumer sequence if some messages were discarded.
=> Fix ordered consumer after discard policy hit

async-nats/CHANGELOG.md, async-nats/Cargo.toml
This release focuses on fixes and improvements, with addition of ordered Push Consumer.
* Add cluster to streaminfo/consumerinfo struct by @j13tw in https://github.com/nats-io/nats.rs/pull/537
* Add `ClusterInfo` and `PeerInfo` by @Jarema in https://github.com/nats-io/nats.rs/pull/572
* Add ordered  push consumer by @Jarema in https://github.com/nats-io/nats.rs/pull/574
* Add concurrent example by @Jarema in https://github.com/nats-io/nats.rs/pull/580
* Add delete message from stream by @Jarema in https://github.com/nats-io/nats.rs/pull/588
* Fix ordered consumer after discard policy hit by @Jarema in https://github.com/nats-io/nats.rs/pull/585
* Fix pull consumer stream method when batch is set to 1 by @Jarema in https://github.com/nats-io/nats.rs/pull/590
* Fix reconnect auth deadlock …
=> Release async-nats/v0.18.0

async-nats/src/client.rs, async-nats/src/lib.rs, async-nats/src/options.rs, async-nats/tests/client_tests.rs
=> Add custom request prefix option

async-nats/src/jetstream/consumer/mod.rs, async-nats/src/jetstream/consumer/pull.rs, async-nats/src/jetstream/consumer/push.rs, async-nats/src/jetstream/context.rs, async-nats/src/jetstream/stream.rs, async-nats/tests/jetstream_tests.rs
=> Use new Consumer API and add Consumer name

async-nats/src/jetstream/consumer/mod.rs, async-nats/tests/jetstream_tests.rs
fixes https://github.com/nats-io/nats-architecture-and-design/issues/122
@caspervonb do we take the liberty of being pre-1.0 and rename `SequencePair` to `SequenceInfo`? I would say - yes.
=> Add last_active to SequenceInfo and rename SequencePair to SequenceInfo

async-nats/src/jetstream/stream.rs, async-nats/tests/jetstream_tests.rs
implements https://github.com/nats-io/nats-architecture-and-design/issues/160#event-7472128440
=> Add discard_new_per_subject to Stream

async-nats/examples/jetstream_pull.rs, async-nats/src/client.rs, async-nats/src/connection.rs, async-nats/src/header.rs, async-nats/src/jetstream/account.rs, async-nats/src/jetstream/consumer/mod.rs, async-nats/src/jetstream/consumer/pull.rs, async-nats/src/jetstream/consumer/push.rs, async-nats/src/jetstream/kv/mod.rs, async-nats/src/jetstream/message.rs, async-nats/src/jetstream/mod.rs, async-nats/src/jetstream/object_store/mod.rs, async-nats/src/jetstream/stream.rs, async-nats/src/lib.rs, async-nats/src/options.rs
This PR fixes a couple of issues that I found with the docs while using the async-nats client.
The issues I found were mostly:
* Typos
* Code Examples without the `#Examples` title
* Code Examples that didn't have ``` , to indicate a code block
=> Fix typos in async-nats docs

async-nats/src/client.rs
=> Add docs to client methods

async-nats/Cargo.toml, async-nats/dependencies.md
`async_nats` already depends on `rustls-native-certs v0.6.2`, which depends on `rustls-pemfile 1.0.1`. This change bumps the version of `rustls-pemfile` depended on directly on that version, so that the direct dependency matches the transitive dependency, preventing the compiler from compiling two different versions of that crate.
=> Bump rustls-pemfile version

async-nats/src/jetstream/consumer/pull.rs, async-nats/tests/jetstream_tests.rs
The previous solution worked only because after some time, something was polled. It was never related to heartbeats one shot `try_recv()`, because, quoting tokio docs
> If no value has been sent, the current task will not be registered for future notification.
I switched to mpsc for simplicity.
=> Fix missing hearbeats future wakup

async-nats/src/jetstream/stream.rs, async-nats/tests/jetstream_tests.rs
=> Add sources and mirror to stream config

async-nats/src/options.rs
Having them as `error` was pretty misleading :).
=> Change event logs to info level

async-nats/tests/jetstream_tests.rs
Small hearbeat interval is not something that should ever happen in production use cases so that is not a good way to test if they're implemented proberly.
Instead, I reduced the number of messages and increased the intervals.
That should have nice test-runs times with less flakyness.
=> Further improve hearbeat tests

async-nats/src/lib.rs
Minor documentation change to use the term subscriber over sub consistently.
=> Use subscriber term consistently

async-nats/src/lib.rs
Connection handler is supposed to exit when all senders are dropped, ping and flush tasks currently keep it alive.
=> Merge periodic ping into connection handler loop

nats/src/proto.rs
1.65.0 release made this a no-go.
=> Remove unsafe vec init

async-nats/src/jetstream/kv/mod.rs
Clarifies K/V purge documentation to record that it is a removal of entries not the key itself from the bucket.
=> Update K/V purge documentation verbiage

async-nats/src/jetstream/object_store/mod.rs
There was no interoperability between Go and Rust client because of this.
=> Fix object store bucket names

.github/workflows/test.yml, async-nats/src/connection.rs, nats/examples/nats-box/main.rs, nats/examples/nats_bench.rs, nats/nats_test_server/src/lib.rs, nats/src/kv.rs, nats/src/object_store.rs, nats/tests/async_errors.rs, nats/tests/auth_nkey.rs, nats/tests/auth_tls.rs, nats/tests/auth_token.rs, nats/tests/auth_user_pass.rs, nats/tests/drop.rs, nats/tests/jetstream.rs, nats/tests/kv.rs, nats/tests/no_messages.rs, nats/tests/no_responders.rs, nats/tests/object_store.rs, nats/tests/reconnection.rs, nats/tests/request_timeout.rs
Invokes clippy directly and uses nightly to avoid a regression that results in a panic every now and then.
Closes https://github.com/nats-io/nats.rs/issues/693
=> Fix broken clippy pipeline and errors

async-nats/src/options.rs, async-nats/tests/client_tests.rs
=> Fix typo in retry_on_initial_connect

async-nats/src/jetstream/consumer/push.rs
I was seeing the following being unexpectedly logged to the console:
```
last seen ok. wait
last seen not ok
last seen ok. wait
last seen ok. wait
last seen not ok
```
=> use debug macro for logging instead of println

async-nats/src/lib.rs
Command sender is no longer cloned, so the loop should now break when all senders (client, subscriber, etc) are closed.
Depends on #681
=> Merge periodic flush into connection handler loop

nats/src/jetstream/mod.rs, nats/src/jetstream/pull_subscription.rs, nats/src/jetstream/push_subscription.rs, nats/src/kv.rs, nats/src/lib.rs, nats/src/object_store.rs
As we're slowly moving away from legacy client, let's disable all examples run.
=> Disable all legacy client example excecution

async-nats/CHANGELOG.md, async-nats/Cargo.toml
This release focuses on fixes around Object Store and customized JetStream Publish.
It also breaks a breaking change, as not all `publish()` methods did return `PublishError`, using the generic `async_nats::Error` instead. This has been fixed.
* Make publish error types consistent by @Jarema in https://github.com/nats-io/nats.rs/pull/727
* Fix object store watch to retrieve only new/changed values by @Jarema in https://github.com/nats-io/nats.rs/pull/720
* Fix stack overflow in object store by @Jarema in https://github.com/nats-io/nats.rs/pull/731
* Add customizable JetStream publish by @Jarema in https://github.com/nats-io/nats.rs/pull/728 request by @andrenth
* Add object store list by @Jarema in https://github.com/nats-io/nats.rs/pull/721
* Add docs lint by @Jarema in …
=> Release async-nats/v0.23.0

async-nats/src/lib.rs
Resets the flush interval after ping forces a flush to avoid redundant flush calls
=> Reset flush interval after ping forces flush

async-nats/src/jetstream/stream.rs, async-nats/tests/jetstream_tests.rs
As @derekcollison mentioned, we will need to change in the future how we handle retrieving deleted message ids, considering big numbers of those.
This reverts unreleased addition to `info`, preventing a breaking change when a new approach lands.
This reverts commit 7ebabc72a243da093b990ce96375a08b655a955b.
=> Revert "Add deleted messages details to stream info"

async-nats/src/message.rs
Fixup a minor documentation mention of the http crate, as we no longer use the http crate for headers.
=> Fix-up message header documentation

async-nats/CHANGELOG.md, async-nats/Cargo.toml
This a minor release intended to release all changes before the long-awaited changes around concrete errors land.
* Fix various spelling mistakes by @c0d3x42 in https://github.com/nats-io/nats.rs/pull/735
* Add spellcheck by @Jarema in https://github.com/nats-io/nats.rs/pull/736
* Reset flush interval after ping forces flush by @caspervonb in https://github.com/nats-io/nats.rs/pull/737
* Add extended purge by @Jarema in https://github.com/nats-io/nats.rs/pull/739
**Full Changelog**: https://github.com/nats-io/nats.rs/compare/async-nats/v0.23.0...async-nats/v0.24.0
=> Release async-nats/v0.24.0

async-nats/src/jetstream/consumer/pull.rs, async-nats/tests/jetstream_tests.rs
=> Fuse the pull consumer Stream after terminal error

nats/nats_test_server/src/lib.rs, nats/src/connect.rs
addresses https://github.com/nats-io/nats-architecture-and-design/issues/178
Rust client behaved adequately, but there were some misleading comments.
=> Remove auth_required comment

.github/workflows/test.yml
New version shipped over the last couple of days, clippy should be working again on stable
=> Use stable channel for clippy

async-nats/src/jetstream/object_store/mod.rs, async-nats/src/jetstream/stream.rs, async-nats/tests/jetstream_tests.rs
Incremental step towards #745.
Soft deprecation since we can.
=> Deprecate `Stream::purge_filter`

async-nats/src/service/mod.rs
https://github.com/nats-io/nats-architecture-and-design/pull/183
=> Add type to service responses

async-nats/src/jetstream/context.rs, async-nats/tests/jetstream_tests.rs
=> Add streams list

async-nats/src/options.rs
Benchmarks improves ~1%.
Much less latency without flushing.
=> Improve defaults for connection

async-nats/src/tls.rs, async-nats/tests/tls_tests.rs
Until now, when TLS was used, native OS certs were always loaded. This should not be the case if CA is provided in rustls config or options.
=> Change TLS to conditionally load native certs

async-nats/src/service/mod.rs, async-nats/tests/service_tests.rs
=> Multiple endpoints service

async-nats/src/jetstream/kv/mod.rs, async-nats/tests/kv_tests.rs
The go client [filters out deleted and purged keys](https://github.com/nats-io/nats.go/blob/66009489432be03ff32e5384a2b502fe88f4c635/kv.go#L909) and the async client was not filtering out those keys. This fixes the behavior to be the same and is also slightly more efficient as we aren't iterating over the _entire_ stream of key value history to get the current keys.
I also included an optional commit that I figured I'd do while I was here. The original documentation for this method suggested that the `keys` method should be returning a `Stream` rather than an iter. So I implemented a stream version of it if desired. This commit can be popped off (or moved to a separate PR) depending on maintainer preference
=> fix(kv): Fixes key listing for async client to match go client 

.config/nats.dic, async-nats/src/status.rs
While const Option::unwrap is not in stable it is possible to write our own const unwrap function.
Fixes #804
No more unsafe code 🔥 
<details> 
<summary>If you are curious how Rust handles panics in const context: pretty well</summary>
```
error[E0080]: evaluation of constant value failed
--> async-nats/src/status.rs:270:13
|
270 |             panic!("Invalid non-zero u16");
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'Invalid non-zero u16', async-nats/src/status.rs:270:13
|
note: inside `new_nonzero_u16`
--> async-nats/src/status.rs:270:13
|
270 |             panic!("Invalid non-zero u16");
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `StatusCode::IDLE_HEARTBEAT`
--> async-nats/src/status.rs:256:55
|
256 |     pub const IDLE_HEARTBEAT: …
```
=> Remove unsafe usages in async-nats

async-nats/src/jetstream/kv/mod.rs
=> Explicitly delete consumer after iterating over kv keys

async-nats/src/connector.rs, async-nats/src/lib.rs, async-nats/src/options.rs
Conditionally includes discovered servers based on a boolean option.
Closes https://github.com/nats-io/nats.rs/issues/806
=> Add `ignore_discovered_servers` connect option

async-nats/CHANGELOG.md, async-nats/Cargo.toml
The main focus of this release is Service API with support for multiple endpoints.
* Add multiple endpoints service by @Jarema in https://github.com/nats-io/nats.rs/pull/791
* Add `Vec` to `ToServerAddrs` impl and improve docs examples by @Jarema in https://github.com/nats-io/nats.rs/pull/802
* Add `ignore_discovered_servers` connect option by @caspervonb in https://github.com/nats-io/nats.rs/pull/809
* Remove unsafe usages in async-nats by @zaynetro in https://github.com/nats-io/nats.rs/pull/813
* Explicitly delete consumer after iterating over kv keys by @Jarema in https://github.com/nats-io/nats.rs/pull/818
* Fix key listing for async client to match Go client  by @thomastaylor312 in https://github.com/nats-io/nats.rs/pull/792
* @thomastaylor312 made their first contribution in …
=> Release async-nats v0.27.0

async-nats/src/jetstream/consumer/pull.rs, async-nats/src/lib.rs, async-nats/tests/jetstream_tests.rs
Until now, if while flushing, reconnection was happening, in case of successful reconnect, flusher would not get the response that flush was successful.
=> Fix flush after reconnect

async-nats/CHANGELOG.md, async-nats/Cargo.toml
A patch release focused solely on important fixes
* Fix no error when auth is not provided but required by @Jarema in https://github.com/nats-io/nats.rs/pull/822
* Fix flush after reconnecting by @Jarema in https://github.com/nats-io/nats.rs/pull/823
* Fix duplicate consumer creation by @thomastaylor312 in https://github.com/nats-io/nats.rs/pull/824
**Full Changelog**: https://github.com/nats-io/nats.rs/compare/async-nats/v0.27.0...async-nats/v0.27.1
=> Release async-nats/v0.27.1

async-nats/examples/kv.rs, async-nats/src/jetstream/kv/mod.rs, async-nats/tests/kv_tests.rs
This is a follow up to #792 (I'll rebase once that is merged). Please see this comment thread for additional details around the discussion of changing this API: https://github.com/nats-io/nats.rs/pull/792#discussion_r1061377564
=> Change keys method to use Stream

async-nats/tests/tls_tests.rs
add test that validates that by default, client does not accept server tls from uknown CA.
Closes #808 
=> Add test for unkown ca

.config/nats.dic, .github/workflows/test.yml, async-nats/src/jetstream/consumer/mod.rs, async-nats/src/jetstream/consumer/pull.rs, async-nats/src/jetstream/consumer/push.rs, async-nats/tests/jetstream_tests.rs
Draft until server PR (https://github.com/nats-io/nats-server/pull/3500) is merged.
=> Add support for consumers with multiple filters

async-nats/tests/jetstream_tests.rs
This test started to flap after changes to publish ack and making it async.
=> Fix flapping ack test

.config/nats.dic, async-nats/Cargo.toml, async-nats/src/jetstream/consumer/mod.rs, async-nats/src/jetstream/consumer/pull.rs, async-nats/src/jetstream/consumer/push.rs, async-nats/src/jetstream/message.rs, async-nats/tests/jetstream_tests.rs
=> Add NAK and backoff support

async-nats/src/jetstream/context.rs, async-nats/tests/jetstream_tests.rs
Adds timeout to request and makes it a builder, also completes https://github.com/nats-io/nats.rs/pull/782
=> Make `Context::request` return `IntoFuture` builder

async-nats/tests/jetstream_tests.rs
This test was flapping because consumers could get deleted before the list was retrieved, if machine running it was slow.
=> Fix flapping test for consumers list

async-nats/src/jetstream/consumer/pull.rs, async-nats/tests/jetstream_tests.rs
Getting any message from consumer, even timeout, should reset the last_seen timer.
=> Update consumer last_seen on status messages and requests

async-nats/CHANGELOG.md, async-nats/Cargo.toml
This release prepares the client for 2.10.0 server release and adds some fixes and improvements.
To use the new features before the server 2.10.0 release, enable `server-2.10` feature.
What was before: 
```rust
AckKind::Nak
``` 
now is:
```rust
AckKind::Nak(Option<std::time::Duration>)
```
Which means a standard NAK example
```rust
let message = messages.next().await?;
message.ack_kind(AckKind::Nak).await?;
```
Now should be used like this
```rust
let message = messages.next().await?;
message.ack_kind(AckKind::Nak(None)).await?;
```
or with custom NAK
```rust
message.ack_kind(AckKind::Nak(Some(std::time::Duration::from_secs(10))).await?;
```
This field is provided only in clustered mode, so it's now properly inline with that.
* Add support for consumers with multiple filters by @Jarema in …
=> Release async-nats/v0.28.0

.github/workflows/test.yml, async-nats/CHANGELOG.md, async-nats/Cargo.toml, async-nats/src/jetstream/consumer/mod.rs, async-nats/src/jetstream/consumer/pull.rs, async-nats/src/jetstream/consumer/push.rs, async-nats/src/jetstream/stream.rs, async-nats/tests/jetstream_tests.rs
Crates with features containing `.` fail to publish.
=> Rename server-2.10 feature name

async-nats/src/jetstream/consumer/pull.rs, async-nats/tests/jetstream_tests.rs
Until now, client relied on the server to send timeouts. This add guards with timer.
=> Improve `batch` and `fetch` pull consumer methods

async-nats/src/connector.rs, async-nats/src/jetstream/consumer/mod.rs, async-nats/src/jetstream/stream.rs, nats/src/jetstream/types.rs, nats/src/options.rs
Fixes linting errors related to the `derive_default_enum` feature, more info [here](https://rust-lang.github.io/rfcs/3107-derive-default-enum.html). 
Also, incorporated some other linter suggestions (getting rid of an unnecessary `into_iter` call).
=> Fix linting errors and suggestions

async-nats/src/lib.rs
Partially addresses https://github.com/nats-io/nats.rs/issues/875
As suggested by @caspervonb I'll split this into multiple PRs.
=> Use `MissedTickBehavior::Skip` for flush interval

async-nats/CHANGELOG.md, async-nats/Cargo.toml
This release focuses on preparing for the 1.0.0 release.
The main highlight is Core NATS concrete errors.
There are also security improvements (@paolobarbolini thanks for your help!) and JetStream API improvements.
New errors returned by Core NATS methods are not boxed anymore.
They themselves are not enums, but follow more flexible approach of `std::io::Error` and expose `kind()` method to get the enum.
All enums implement `PartialEq` for more straightforward assertions.
* Add support for stream subject transform by @n1ghtmare in https://github.com/nats-io/nats.rs/pull/867
* Add retaining server list order option by @Jarema in https://github.com/nats-io/nats.rs/pull/890
* Fix a typo in the documentation by @marcusirgens in https://github.com/nats-io/nats.rs/pull/864
* Fix reconnect burst …
=> Release async-nats/v0.29.0

async-nats/src/jetstream/kv/bucket.rs, async-nats/src/lib.rs
Split out of #876 because of breaking changes to the public API
=> Prefer returning `&str` over String where applicable

async-nats/src/jetstream/consumer/pull.rs
usize is too small in 32-bit environments, especially since it is initialized with 30 seconds, i.e. 30_000_000_000 nanoseconds which is already bigger than 2**32.
=> async_nats: pull: Use u64 instead of usize for nanoseconds

async-nats/Cargo.toml, async-nats/src/connector.rs, async-nats/src/jetstream/object_store/mod.rs, async-nats/src/jetstream/stream.rs, async-nats/src/options.rs, async-nats/tests/object_store.rs
Updates the `base64` crate to 0.21 and uses it everywhere for base64 url-safe encoding and decoding.
Let me know if you like the small module I created to wrap the `base64` API with something easier to use or if you'd prefer calling `base64` directly
=> Update `base64` crate and use it in place of `base64-url`

async-nats/Cargo.toml, async-nats/src/tls.rs
Addresses: #882 
`tokio-rustls 0.24` uses `rustls 0.21.0`
Note that `webpki` had to be updated as well since it has been removed from the public API of the new version of `tokio-rustls` (For reference: https://github.com/tokio-rs/tls/pull/82)
=> Bump `tokio-rustls` version and add `webpki` as a dependency

.github/workflows/test.yml
As actions-rs/toolchain@v1 is no longer maintained and will break soon, we're moving to dtolnay/rust-toolchain@stable
=> Remove outdated `actions-rs` github actions

async-nats/src/jetstream/context.rs, async-nats/tests/jetstream_tests.rs
Derek asked about a direct method to avoid one additional call to the server.
Useful mostly when you get very few Consumers and latency is critical.
=> Add Context::get_consumer_from_stream

nats/src/object_store.rs, nats/tests/object_store.rs
Renames the `modified` field to `mtime` for the legacy NATS client.
=> Fix serialization of `ObjectInfo` fields

async-nats/src/header.rs
=> Canonicalize `header::NATS_LAST_STREAM`

async-nats/src/jetstream/kv/mod.rs
Changes key-value Entries to represent payloads as `Bytes` for consistency with the input interface, e.g `put` which does take `Bytes`.
=> Use `Bytes` for key-value payloads

.config/nats.dic, async-nats/src/jetstream/message.rs, async-nats/tests/jetstream_tests.rs
`acker()` splits [Message] into [Acker] and [crate::Message]. This can help reduce memory footprint if [Message] can be dropped before acking, for example when it's transformed
into another structure and acked later.
=> Add `jetstream::Message` `Acker`

async-nats/src/lib.rs
This type is just used internally to communicate with the internal connection handler and not publicly useful to anyone.
=> Make `ClientOp` private

async-nats/src/header.rs
Closes https://github.com/nats-io/nats.rs/issues/942
=> Disallow new lines in `HeaderValue::from_str`

.github/workflows/test.yml
GitHub was complaining about the action being out of date.
=> Bump `actions/checkout` to v3

async-nats/src/header.rs, async-nats/tests/jetstream_tests.rs
Add const representation (an enum) for standard known header names.
Closes https://github.com/nats-io/nats.rs/issues/945
=> Add const representation for standard header names

async-nats/src/header.rs
Removes redundant tokio bootstraps from header examples.
=> Simplify header documentation examples

async-nats/src/jetstream/context.rs
When trying to share an object store between *Rust* & *Go*, it fails with `stream name already in use`. This is caused by a different configuration, here a missing `allow_direct`
Equivalent code in go :
https://github.com/nats-io/nats.go/blob/main/object.go#L282
=> fix(ObjectStore): Fix compatibility issue with Go implementation

async-nats/src/jetstream/kv/mod.rs
It looks like the code for calling update on a KV bucket doesn't include the JS domain on it, so it gives you an error when attempting to make that call.
=> Fix KV update so that it works properly with a JS domain

async-nats/Cargo.toml, async-nats/src/header.rs, async-nats/src/message.rs, async-nats/src/status.rs
This change makes it so an entire message can be serialized/deserialized via serde. Specifically, this addresses the use case of wanting to capture messages and write them to disk for later inspection and/or use
=> feat(message): Makes `Message` serialize/deserialize

.config/nats.dic, async-nats/Cargo.toml, async-nats/src/client.rs, async-nats/src/jetstream/consumer/mod.rs, async-nats/src/jetstream/consumer/pull.rs, async-nats/src/jetstream/consumer/push.rs, async-nats/src/jetstream/context.rs, async-nats/src/jetstream/errors.rs, async-nats/src/jetstream/kv/mod.rs, async-nats/src/jetstream/mod.rs, async-nats/src/jetstream/response.rs, async-nats/src/jetstream/stream.rs, async-nats/src/lib.rs, async-nats/tests/jetstream_tests.rs
=> Add concrete error types to JetStream

async-nats/src/lib.rs
This makes the `Error` type work with `anyhow` (and I guess a few more crates) that [need the error to be `'static`](https://docs.rs/anyhow/1.0.71/anyhow/struct.Error.html#impl-AsRef%3Cdyn+Error+%2B+Sync+%2B+Send+%2B+'static%3E-for-Error)
=> Make the current `Error` type work with anyhow

async-nats/src/jetstream/consumer/pull.rs
=> Add Pull Consumer concrete errors

async-nats/src/jetstream/consumer/push.rs, async-nats/src/jetstream/object_store/mod.rs
A quick fix for ordered push consumer not being dropped as soon as object from Object Store is read.
`Object` might be valid for quite some time, so the subscription is running for no reason.
=> Drop subscription on object read done

async-nats/Cargo.toml
Today rustls 0.21.3 came out and it upgraded to rustls-webpki v0.101. They can do this because they don't expose the dependency in their public API, so it's not a breaking change for them to do. This means though that now we have to compile two different versions of the same dependency. This fixes it by realizing the rustls-webpki versions.
=> Bump rustls-webpki to v0.101.1

async-nats/src/jetstream/object_store/mod.rs, async-nats/src/jetstream/stream.rs
=> Add concrete errors to Object Store

async-nats/Cargo.toml, async-nats/src/tls.rs
Until now, we did depend on tokio-rustls re-export of rustls.
Re-export is ^0.21.0, so patch releases are allowed.
However, as rustls released 0.21.4, it introduced
a breaking change in patch release, breaking the async-nats client build.
To avoid that in the future, we do not use re-export, but bind directly to rustls explicit version.
When rustls reaches 1.0.0, we can reconsider binding to ^1.0.0.
Related issues: #1017 #1018 
=> Depend directly on rustls

async-nats/Cargo.toml, async-nats/src/tls.rs
Reverts nats-io/nats.rs#1020
Unfortunately, this can cause conflicts and issues in crates depending on `async-nats`.
=> Revert "Depend directly on rustls"

async-nats/tests/jetstream_tests.rs
This tests takes 40 minutes on my Linux machine and is very slow on my mac (M2) as well.
=> Mark `pull_sequence` as a slow test

async-nats/src/service/mod.rs, nats/src/lib.rs
=> Remove error on lint warnings for legacy client

async-nats/CHANGELOG.md, async-nats/Cargo.toml
This is a big release that introduces almost all breaking changes and API refinements before 1.0.0.
The last two pending breaking items are: 
* Improved builders based on https://github.com/nats-io/nats.rs/discussions/828
* Introduce a `Subject` type (still discussed)
* Make `publish` etc return an `into_future` based builder.
* Update Service for parity with ADR by @Jarema in https://github.com/nats-io/nats.rs/pull/965
* Remove schema and api_url from Service API by @Jarema in https://github.com/nats-io/nats.rs/pull/972
* Add concrete error types to JetStream by @Jarema in https://github.com/nats-io/nats.rs/pull/874
* Add concrete errors to KV by @Jarema in https://github.com/nats-io/nats.rs/pull/1014
* Add concrete errors to Object Store by @Jarema in …
=> Release async-nats/v0.30.0

async-nats/src/jetstream/consumer/push.rs
Simplifies some of the code I was reading while debugging https://natsio.slack.com/archives/CLNJ3BQNB/p1689585858761889
=> Simplify consumer checking logic

async-nats/src/jetstream/object_store/mod.rs
Removes a memcpy from the object store PUT implementation and a [scary](https://github.com/rust-lang/rust/issues/53827) `Box::new` with a huge array
=> Remove memcpy in object store PUT

async-nats/src/jetstream/consumer/pull.rs, async-nats/tests/jetstream_tests.rs
=> Rework idle heartbeat for pull consumers

async-nats/CHANGELOG.md, async-nats/Cargo.toml
This release focuses on improvements of heartbeats in JetStream Consumers.
Heartbeats are a tool that tells the user if the given consumer is healthy but does not get any messages or if the reason for no message is an actual problem.
However, if the user was not polling the `Stream` future for the next messages for a long time (because it was slowly processing messages), that could trigger idle heartbeats, as the library could not see the heartbeat messages without messages being polled.
This release fixes it by starting the idle heartbeat timer only after Stream future is polled (which usually means calling `messages.next().await`).
* Fix unwrap from `HeaderName::from_str` call by @caspervonb in https://github.com/nats-io/nats.rs/pull/1032
* Use idiomatic method for writing `Option` and …
=> Release async-nats v0.31.0

async-nats/src/connection.rs
Cleans up `ServerOp` parsing by reducing panicking branches, allocations plus other improvements.
=> Tidy up `ServerOp` parsing

async-nats/src/jetstream/object_store/mod.rs
Removes a memcpy and an allocation from the object read implementation
=> Optimize `GET`ting and object's payload

async-nats/src/auth_utils.rs, async-nats/src/options.rs
I don't know if this is documented anywhere but this is the style used by all APIs that deal with the filesystem. Sometimes it even gets used when a `PathBuf` would have been the better choice when it comes to heap allocations, because it's nicer to use.
The reason why this is the preferred method is that [a bunch of things implement `AsRef<Path>`](https://doc.rust-lang.org/nightly/std/path/struct.Path.html#trait-implementations), including `&str`, so it avoids the manual cast to `&Path` or memcpy to `PathBuf`.
=> Take `impl AsRef<Path>` instead of `PathBuf` in credentials APIs

async-nats/src/jetstream/kv/mod.rs
Tidy up the KV operations a bit.
=> Implement `FromStr` for `jetstream::kv::Operation`

async-nats/src/jetstream/consumer/pull.rs
=> Use `Duration` in a few more places

async-nats/src/client.rs, async-nats/src/error/mod.rs, async-nats/src/jetstream/consumer/mod.rs, async-nats/src/jetstream/consumer/pull.rs, async-nats/src/jetstream/consumer/push.rs, async-nats/src/jetstream/context.rs, async-nats/src/jetstream/kv/mod.rs, async-nats/src/jetstream/object_store/mod.rs, async-nats/src/jetstream/stream.rs, async-nats/src/lib.rs, async-nats/src/nats_error.rs
While trying to recognize how the gem works I found this [TODO](https://github.com/nats-io/nats.rs/blob/main/async-nats/src/lib.rs#L1346) and decided to implement it (well, this is how I learn things).
But at the moment the implementation got ready, I asked myself, why the same functionality cannot be expressed better with generic structs, and found no answer. That's why instead of implementing another macro (derive or attribute), I restarted my refactoring from scratch and removed the very necessity of the macro in favor of `NatsError<T>`.
This type represents any error to be raised by the crate. It is generic over the enum representing the kind of the error.
Unlike the previous code where binding between the kind and the error used to be provided by the macro `error_impls`, this …
=> [Refactoring] Use a generic error type instead of the macro `error_impls`

async-nats/src/jetstream/context.rs
This is only a minor change which makes the comment on `Context::get_object_store` a bit clearer - the former comment was the same as on `create_object_store`.
=> Clearer documentation for Context::get_object_store

async-nats/src/tls.rs
#1017 was reported as a breaking change made to `rustls`. This isn't really the case. The true culprit is this vague `.as_ref()` call.
In general, it is allowed to change a fn that used to take `T` to now take `impl Trait` where `T: Trait`. `AsRef` is an unfortunate example of a trait that is often misused like this.
There may be more of these cases, if possible they should be switched so that a new `AsRef` impl or change such as was made in `rustls` doesn't break downstreams again.
=> Fix potentially ambiguous `.as_ref()`

.config/nats.dic, async-nats/src/jetstream/object_store/mod.rs, async-nats/tests/object_store.rs
=> Add update metadata

async-nats/src/header.rs, async-nats/src/jetstream/consumer/pull.rs, async-nats/src/jetstream/consumer/push.rs, async-nats/src/jetstream/kv/mod.rs, async-nats/tests/jetstream_tests.rs, async-nats/tests/service_tests.rs
Closes https://github.com/nats-io/nats.rs/issues/925
=> Introduce `get` and `get_all` semantics to `HeaderMap`

async-nats/Cargo.toml, async-nats/benches/core_nats.rs, async-nats/benches/jetstream.rs, async-nats/benches/main.rs
* adds jetstream publish and publish async benchmarks
* renames benchmark groups to allow calling specific bench:
```
cargo bench
cargo bench nats
cargo bench nats::request
```
=> Add jetstream benchmarks

async-nats/Cargo.toml, async-nats/src/jetstream/object_store/mod.rs, async-nats/tests/object_store.rs
=> Add object store link

async-nats/Cargo.toml
This bump is done to avoid relying on serde 1.0.172 release, which had precompiled binary included, that has been reverted in 1.0.184
1.0.184 release: https://github.com/serde-rs/serde/releases/tag/v1.0.184
fix: https://github.com/serde-rs/serde/pull/2590
context: https://github.com/serde-rs/serde/issues/2538
supersedes: #1092 
=> Bump serde to 1.0.184

async-nats/src/jetstream/consumer/pull.rs
=> correct spelling mistake in jetstream/consumer/pull

async-nats/src/options.rs
Issue: ping_interval example was calling flush_interval
Also, Use duration::from_secs
=> fix/doc: Typo in ping_interval example

nats-server/Cargo.toml, nats-server/src/lib.rs
This patch fixes the [cargo-deny](https://github.com/EmbarkStudios/cargo-deny)'s security warning for `nats-server` which is used by `async-nats`:
```shell
$ cargo-deny --exclude nats --exclude nats_test_server check
```
which reported:
```
┌─ ../nats.rs/Cargo.lock:83:1
│
83 │ json 0.12.4 registry+https://github.com/rust-lang/crates.io-index
│ ----------------------------------------------------------------- unmaintained advisory detected
│
= ID: RUSTSEC-2022-0081
= Advisory: https://rustsec.org/advisories/RUSTSEC-2022-0081
= Last release was almost 3 years ago.
The maintainer is unresponsive with outstanding issues.
```
After the fix `cargo-deny` got satisfied
```
advisories ok, bans ok, licenses ok, sources ok
```
=> Switch dependency: json->serde_json in nats-server

async-nats/Cargo.toml
Here I checked and then fixed minimal versions for transitive dependencies of the `async-nats`.
```shell
cargo +nightly update -Zminimal-versions
cargo check --package async-nats --all-targets
```
After the fixes it got green.
See detailed explanations in the commit messages
=> Fix minimal versions

async-nats/Cargo.toml, async-nats/src/client.rs, async-nats/src/connection.rs, async-nats/src/connector.rs, async-nats/src/jetstream/consumer/pull.rs, async-nats/src/jetstream/consumer/push.rs, async-nats/src/jetstream/context.rs, async-nats/src/lib.rs, async-nats/src/options.rs, async-nats/tests/kv_tests.rs
This is an attempt at refactoring `Connection`  and `ConnectionHandler` to use `poll` instead of `async` `.await` syntax.
Advantages:
1. Ability to continue reading while in the middle of writing: previously a write operation would block read operations from happening. Now as soon as an operation returns `Poll::Pending` the other operations can be polled
2. Ability to continue reading and writing while in the middle of flushing: previously flushing blocked everything else until it completed
3. Easier control of connection state and reduced error branches because of centralized connection error handling
4. Removal of `select!` from a very critical path. The issues with it are the following:
* It relies on the `Future`s polled by it's branches to be _cancel safe_. Cancel safety requires …
=> Refactor connection handling

.config/nats.dic, async-nats/src/jetstream/stream.rs, async-nats/tests/jetstream_tests.rs
=> Add new Stream Config 2.10 fields

.github/workflows/test.yml, async-nats/tests/jetstream_tests.rs
Dev branch has been made obsolete after 2.10 release. New release model will not have dev branch.
=> Remove dev branch tests

async-nats/src/service/endpoint.rs, async-nats/src/service/mod.rs, async-nats/tests/service_tests.rs
=> Fix service Info to include endpoints info

.github/workflows/main.yml, .github/workflows/test.yml
In this PR I tried to improve the CI in several aspects. Below is the description of commits in this PR:
The incremental build is a way to fasten future compilations for the cost of extra dependency tracking and bigger /target.
This <default> approach is not necessary in the CI because every compilation is done from scratch.
As a result of turning it off the size of the target reduces from 660MB to 543MB.
This change reduces the size of the /target directory from 543MB to 424MB without (or from 660MB to 483MB with) the incremental compilation.
The primary difference is that this GHA caches not the whole content of the `./target` but only dependencies. Along with points 1 and 2 this makes caches 3x smaller (230-450MB instead of 0.8-1.3GB) for the same build time.
This enables to store the …
=> Improve CI/CD

async-nats/src/connection.rs, async-nats/src/lib.rs
This cleans-up the flushing logic from #1060.
This change makes it so `flush` is interrupted (doesn't get polled anymore) when new writes are in progress. The reason for this is that if a write returns `Poll::Pending` either the downstream write buffers are full already or [tokio decided to force a yield to the executor](https://docs.rs/tokio/1.32.0/tokio/task/index.html#cooperative-scheduling). In either case there's no advantage in explicitly trying to flush.
Before:
* Successfully write first command
* No more commands are available
* Start `flush`ing. Operation is `Poll::Pending`
* Get a second command and start writing it, getting `Poll::Pending` in the middle of writing it
* Call `flush` again. `Poll::Pending` is almost always guaranteed here.
After:
* Successfully write first …
=> Cleanup flush logic

async-nats/src/lib.rs
=> Fix muxer prefix

async-nats/src/jetstream/object_store/mod.rs
As some libraries might omit fields in structs when creating Object Store links, (as link and object have different always-filled fields, but they share the same schema) this change is to make it work with them.
=> Make object store structures more resilient

async-nats/src/client.rs, async-nats/src/jetstream/context.rs
This makes Jetstream publishes re-use the muxed subscriber logic from #1069.
I'm not really happy with the implementation, but the current internal API is quite strict on what it allowed.
=> Use muxed inbox to handle jetstream publishes

async-nats/src/jetstream/context.rs, async-nats/src/jetstream/kv/mod.rs, async-nats/src/jetstream/stream.rs
=> Add compression option to kv

.github/workflows/test.yml, async-nats/src/connector.rs, async-nats/src/lib.rs, async-nats/src/options.rs, async-nats/tests/configs/tls_first.conf, async-nats/tests/configs/tls_first_auto.conf, async-nats/tests/tls_tests.rs
NATS server used to send INFO when client connected, before establishing TLS.
As server added support to establish TLS before getting any INFO, this commit adds `tls_first` option to be able to used that feature.
=> Add TLS first support

async-nats/src/service/mod.rs
Proposed fix for https://github.com/nats-io/nats.rs/issues/1151.
I wasn't crazy about any of the options for dividing a `Duration`.
The problem w/ [checked_div](https://doc.rust-lang.org/stable/std/time/struct.Duration.html#method.checked_div) is that it only takes `u32` and total_requests is `usize`.
I considered div_f64, but just doing the calculation as nanos and converting back to a Duration seems fool-proof and panic-free.
=> Calculate average processing time as total time / # requests

nats/src/auth_utils.rs
Fixes issue https://github.com/nats-io/nats.rs/issues/1126
=> chore: fix sync TLS authentication for EC keys

async-nats/src/service/mod.rs
Removes an accidentally committed `println!` in the service initialization code.
=> Remove println

.github/workflows/test.yml
To prevent problems like https://github.com/nats-io/nats.rs/issues/1090 maybe it makes sense to check transitive dependencies in the CI.
I also had to fix another dependency `openssl` restricted from `0.10.29` -> `0.10.36` (the latest one is `0.10.55`)
=> Check min versions of transitive depencencies in CI

async-nats/Cargo.toml
Num is used by fraction, which in used by json-schema, which we use in testing.
In 4.0, signatures were a bit different, so it failed to compile.
=> Specify num indirect dependency min version

async-nats/src/jetstream/consumer/pull.rs
Ordered consumer does not need to deliver an ACK (uses AckNone).
=> Fix ordered-consumer example

async-nats/src/service/endpoint.rs, async-nats/tests/service_tests.rs
There were 2 issues in the stop system for services :
- On the first poll of the stream, the shutdown future was not polled, thus stopping the service would never wake this task
- After the shutdown future is resolved, the next poll will still poll the shutdown future, which is not allowed
=> Fix Service::stop

async-nats/src/subject.rs
This should allow for easier conversion back into a `String`, possibly without an allocation if the underlying data is already owned
=> feat(subject): Adds `into_string` method to `Subject`

async-nats/Cargo.toml, async-nats/dependencies.md, async-nats/src/header.rs
This was only used for generating a documentation link. I've changed it to not link to the `http::header` docs at all, but this could also be made a manual link to docs.rs if that's preferred.
=> Remove unused dependency on http

async-nats/src/header.rs, async-nats/src/subject.rs
The default derives produce a very ugly serialization format for these wrappers. Since they are guaranteed to be strings it makes sense to serialize/deserialize them directly as strings.
This also makes it possible to implement Object Store object headers, since they need to deserialize a HeaderMap from JSON.
=> Serialize/Deserialize Subject and HeaderName as strings

async-nats/src/jetstream/consumer/pull.rs, async-nats/tests/jetstream_tests.rs
=> Terminate fetch on `No Messages`

.github/workflows/main.yml
After adding much more benchmarks, it seems that this is too much for Github Actions. Running only Core Nats benchmarks should be enough for tracking general client performance.
=> Run bench on CI only for Core Nats

async-nats/Cargo.toml, async-nats/src/connector.rs, async-nats/src/options.rs, async-nats/src/tls.rs, async-nats/tests/tls_tests.rs
=> Update rustls to v0.22 and related dependencies

async-nats/src/jetstream/consumer/pull.rs, async-nats/src/jetstream/consumer/push.rs, async-nats/src/jetstream/context.rs, async-nats/src/jetstream/kv/mod.rs, async-nats/src/jetstream/object_store/mod.rs, async-nats/src/jetstream/stream.rs
Based on #1166 
`ObjectStore::get` calls itself recursively, so the returned future needs to be boxed. However, this is an implementation detail, there's no reason to expose it in the public API. Instead, we can move the recursive call to a separate `get_impl` function that handles the boxing, and `get` can just be a standard async function.
This is a minor stylistic change, but if it's desired it makes sense to land it at the same time as #1166 since that is already a breaking change.
=> Don't expose BoxFuture in public API

async-nats/src/jetstream/context.rs, async-nats/src/jetstream/stream.rs
As usual, rust toolchain after update catches few more things while linting.
This one simplify links labels and fixes one broken link.
=> Fix and simplify docs links

Cargo.toml, nats/Cargo.toml
cargo warned about
* profiles are ignored anywhere but in the top-level manifest
* the resolver was at version 1, while edition 2021 was implying
resolver = "2"
After comments on this pr, the workspace profiles were removed entirely.
=> Fix minor cargo workspace warnings

async-nats/src/options.rs
Docs for `ConnectOptions::retry_on_initial_connect` and `ConnectOptions::ignore_discovered_servers`.
=> fix #1180: Add missing docs for ConnectOptions

.config/nats.dic, async-nats/src/connector.rs, async-nats/src/lib.rs, async-nats/src/options.rs, async-nats/tests/client_tests.rs
Supersedes #1187 with a clean history.
Thank you @glueball for you contribution!
=> Add max reconnects to public API

async-nats/examples/kv.rs, async-nats/src/jetstream/kv/mod.rs, async-nats/tests/kv_tests.rs
[Similar to the nats.net.v2 client](https://github.com/nats-io/nats.net.v2/blob/main/src/NATS.Client.KeyValueStore/NatsKVStore.cs#L131), an option to add the expected revision was added. A delete or purge will be rejected similar to the update function.
This is needed to make better use of the immediately consistent properties of the kv store.
This is a breaking change, as all references to current deletes or purges will have to be updated to include a None.
=> Add revision to kv operations

async-nats/src/connector.rs, async-nats/src/lib.rs
Turns out `ServerAddr::socket_addrs` was blocking the tokio runtime because it used the std blocking implementation for doing DNS lookups. This switches to the `tokio` implementation, which internally does a `spawn_blocking` of the std call.
=> Do asynchronous DNS lookups in `ServerAddr::socket_addrs`

async-nats/Cargo.toml
Changes: https://github.com/wasmCloud/nkeys/compare/v0.3.2...v0.4.0
=> Bump nkeys to 0.4

.config/nats.dic, async-nats/src/jetstream/kv/mod.rs, async-nats/tests/kv_tests.rs
Addreses https://github.com/nats-io/nats-architecture-and-design/issues/261#event-11390045923
=> Add watch from revision for KV

async-nats/Cargo.toml, async-nats/src/connector.rs, async-nats/src/jetstream/consumer/pull.rs, async-nats/src/jetstream/consumer/push.rs, async-nats/tests/jetstream_tests.rs
This PR adds few improvements to ordered consumers:
- It will recreate ordered pull consumers if `heartbeats` are missed twice
- It will retry all push and pull ordered consumer recreation API calls to have chance of success in case  of network/consensus instasbilities
- Add more tracing
Above provide smoother experience for working with ordered consumers in unstable network/consensus/extreme load conditions.
This PR also replaces `tokio_retry` with (tryhard)[https://github.com/EmbarkStudios/tryhard], ask I found bug in how `tokio_retry` counts backoffs. Also `tryhard` is actively maintained by a well know entity.
=> Recreate ordered pull on heartbeats

async-nats/src/lib.rs
When an interval is ready, it does not need to register its internal waker, leading to the future not being polled anymore if the connection received no data.
The fix is pretty simple, and it should never cause any problems unless the interval duration is very close to zero, which will probably cause strange issues anyway.
=> fix: ensure the ping interval waker is registered

async-nats/src/jetstream/consumer/pull.rs, async-nats/src/jetstream/context.rs, async-nats/src/jetstream/stream.rs, async-nats/tests/jetstream_tests.rs
This Pull requests optimizes how we handle recreating Ordered Consumers by not calling Stream Info, as we don't need it.
It also adds ability to delete and create a consumer directly on the `Context`.
=> Optimize consumer recreate

async-nats/Cargo.toml, async-nats/src/lib.rs
Tokio 1.36 exposed [`Receiver::poll_recv_many`](https://docs.rs/tokio/1.36.0/tokio/sync/mpsc/struct.Receiver.html#method.poll_recv_many), which allows polling multiple items at once from an mpsc channel. Considering that our write buffer already has a lenient capacity limit, and the benchmarks show that the reduced overhead is worth it, this PR makes the connection handler poll 16 commands at once instead of just 1.
<details>
<summary>Benchmark results (Ryzen 5900X)</summary>
```
Gnuplot not found, using plotters backend
nats::publish_throughput/32
time:   [86.357 ms 91.881 ms 95.353 ms]
thrpt:  [160.02 MiB/s 166.07 MiB/s 176.69 MiB/s]
change:
time:   [-27.813% -21.773% -15.602%] (p = 0.00 < 0.05)
thrpt:  [+18.487% +27.834% +38.529%]
Performance has improved.
nats::publish_throughput/1024 …
```
=> Use poll_recv_many for processing commands to be written to the nats server

async-nats/src/subject.rs
The whole point of having a `from_static` function is to use it in a const context :wink:
=> Make `Subject::from_static` a const fn

async-nats/src/error.rs
A lot of errors do contain source, but the Error type did not actually implement the `source()` method and was always returning `None`, using the default implementation. Thanks @hseeberger and @thomastaylor312 for reporting this indirectly.
=> Add source implementation for Error

async-nats/src/jetstream/context.rs, async-nats/src/jetstream/mod.rs, async-nats/src/jetstream/stream.rs
fixes #1213 
The new validation function does also check for empty name, but we keep separate check for Stream methods for consistency across Stream API.
=> Add stream name check to all stream management methods

async-nats/src/jetstream/context.rs, async-nats/src/jetstream/object_store/mod.rs
This addresses ADR requirement https://github.com/nats-io/nats-architecture-and-design/issues/265
=> Add compression to object store

async-nats/src/client.rs, async-nats/src/connector.rs, async-nats/src/lib.rs, async-nats/tests/client_tests.rs, async-nats/tests/configs/max_payload.conf
This adds check if the messages Client is publishing to a server it is connected too does not exceed `max_payload`.
This unfortunately asks for changing the error from a simple struct that maps error from `mpsc` error to a new one.
Tests of how disruptive the error change is is under progress, hence the Draft.
We are using new `Atomic` instead of relying on the server info watcher for performance reasons.
=> Add check for max payload size when publishing messages

async-nats/Cargo.toml
`base64` is one of those dependencies that get used by everybody and ends up finding itself into projects in the form of multiple duplicate versions. Since you're about to make a release let's do our part in not having duplicate versions of it :smiley:.
Changelog: https://github.com/marshallpierce/rust-base64/blob/master/RELEASE-NOTES.md#0220
=> Bump base64 to v0.22

async-nats/CHANGELOG.md, async-nats/Cargo.toml
This release introduces performance improvements (thanks to poll_recv_many #1189), improves resilience of
ordered consumers by recreating them in more cases while having less server calls. It also adds some new features.
Breaking changes are minor, however, all are worth mentioning.
* Don't expose BoxFuture in public API by @oscarwcl in https://github.com/nats-io/nats.rs/pull/1167
This change simplifies lifetimes of Boxed Futures, by making them static. It should not affect most users,
and if it does, removal of the lifetime should be a quick fix.
* Add check for max payload size when publishing messages by @Jarema in https://github.com/nats-io/nats.rs/pull/1211
The client was not checking if the message payload size was not exceeding the limits of the server it is connected to.
While …
=> Release async-nats/v0.34.0

async-nats/src/jetstream/message.rs
In some cases manual Acker creation is preferable, than usage `.split` method. That's public fn constructor introduction.
=> Add public constructor for Acker

async-nats/src/client.rs
The goal of the `Client` struct was to be a clonable handle. However, the struct contained a bare string that was cloned each time. In apps that clone the client regularly, this lead to quite a few allocations.
This is a non-breaking change purely internal to the client
=> feat(client): Wraps inbox prefix in an `Arc`

.config/nats.dic, async-nats/src/client.rs, async-nats/src/lib.rs, async-nats/tests/client_tests.rs
reference ADR issue: https://github.com/nats-io/nats-architecture-and-design/issues/259
=> Add force reconnect

README.md, async-nats/Cargo.toml
Addresses #1243 
As there is no good way in Rust to document feature flags beyond listing them, adding comments to `Cargo.toml` seems to be the best answer.
The link in the Readme directs to the `Cargo.toml` from latest release, which should avoid docs drift.
=> Document feature flags

async-nats/src/header.rs, async-nats/src/jetstream/consumer/push.rs, async-nats/src/jetstream/kv/mod.rs, async-nats/tests/kv_tests.rs
As republish will append new headers, using first value could lead to misleading data when a message is republish from one stream to another.
This commit fixes it by always picking the last header value.
reference ADR issue: https://github.com/nats-io/nats-architecture-and-design/issues/250
Signed-off-by: Tomasz Pietrek <tomasz@nats.io
=> Use last header value for JetStream messages

.github/workflows/test.yml
The latest nats-server build seems to fail, but only on github actions CI.
Disabling windows CI until it's fixed.
=> Update Go version in CI

.config/nats.dic, async-nats/src/jetstream/context.rs, async-nats/src/jetstream/errors.rs, async-nats/src/jetstream/stream.rs, async-nats/tests/jetstream_tests.rs
We decided to not change behavior of `create_consumer`, as this would be a breaking change that does not show up during compile time.
=> Add consumer action

async-nats/src/connection.rs, async-nats/src/lib.rs
It turns out `poll_write` could return `Poll::Pending` while `poll_flush` could flush successfully (`Poll::Ready`). This seems like a rare case, although possible in theory.  This fixes it by actually making it behave the way it was described in the original PR https://github.com/nats-io/nats.rs/pull/1060#issuecomment-1657242359
=> Don't force flush if write buffer isn't empty

.github/workflows/test.yml, async-nats/Cargo.toml, async-nats/src/crypto.rs, async-nats/src/jetstream/object_store/mod.rs, async-nats/src/lib.rs, async-nats/tests/compatibility.rs, async-nats/tests/object_store.rs
Depends on https://github.com/rustls/tokio-rustls/pull/59
=> Upgrade rustls to v0.23 and add support for aws-lc-rs

.github/workflows/test.yml, async-nats/src/error.rs, async-nats/src/lib.rs
It is actually not used anywhere beyond tests and causes linter to complain
=> Remove the WithKind trait

async-nats/CHANGELOG.md, async-nats/Cargo.toml
This release makes tls setup more flexible, leveraging rusls v0.23 and allowing to pick crypto backend:
* ring
* aws-lc-rs
* fips
Some other highlights:
* force reconnect via `force_reconnect` method
* explicit create/update consumer API
Thank you for all your contributions!
* Add `ToServerAddrs` impl for array/vector of strings by @mmalek in https://github.com/nats-io/nats.rs/pull/1231
* Add public constructor for Acker by @AbstractiveNord in https://github.com/nats-io/nats.rs/pull/1232
* Add force reconnect by @Jarema in https://github.com/nats-io/nats.rs/pull/1240
* Add features check by @Jarema in https://github.com/nats-io/nats.rs/pull/1247
* Add stream placement by @Jarema in https://github.com/nats-io/nats.rs/pull/1250
* Add consumer action by @Jarema in …
=> Release async-nats/v0.35.0

async-nats/Cargo.toml
The docs.rs build is failing because of the fact, that the `fips` dependency while compiling, tries to write some files, which is not allowed in read-only docs.rs environment.
=> Fix docs.rs build

async-nats/src/lib.rs
Server errors can contain case-sensitive values like subject names which can cause confusion if not displayed in their original case.
This was motivated by this error: `nats: permissions violation for publish to "$js.api.stream.info.kv_test"`, which is misleading since the actual subject is `$JS.API.STREAM.INFO.KV_test`.
=> Preserve case of server error messages

async-nats/CHANGELOG.md, async-nats/Cargo.toml
This release fixes broken docs build caused by `fips`, which cannot be built in restricted docs.rs environment.
* Fix docs.rs build by @Jarema in https://github.com/nats-io/nats.rs/pull/1259
* Preserve case of server error messages by @oscarwcl in https://github.com/nats-io/nats.rs/pull/1258
**Full Changelog**: https://github.com/nats-io/nats.rs/compare/async-nats/v0.35.0...async-nats/v0.35.1
=> Release v0.35.1

async-nats/src/lib.rs
This PR adds `client.flush()` calls to publish examples in the documentation to help avoid potential confusion when messages aren't immediately published due to buffering (in fact, on my short-lived CLI app they weren't being sent at all). See https://github.com/nats-io/nats.rs/issues/773#issuecomment-2119116600.
@Jarema I actually have a few questions in regards to this:
1. is `flush()` supposed to be called on a regular basis if not publishing too frequently?
2. do you mind briefly explaining to me how the buffering works in this case? is it only count-based or time-based too?
3. how could I tweak it so that it flushes more frequently by itself?
=> Add `client.flush()` calls to example code in docs

async-nats/src/options.rs, async-nats/tests/jetstream_tests.rs
supersedes #1249 
supersedes #1237
=> Removes dead code carried over from the old client

.config/nats.dic, async-nats/src/client.rs, async-nats/src/jetstream/context.rs, async-nats/tests/jetstream_tests.rs
If client was created with `retry_on_initial_connect` and `create_consumer_on_stream` was called immediately afterwards, it could cause a panic, as semver regex capture would fail on empty string.
This PR removes the validation, as it was never a reliable way to check server version, as the meta leader can be a different version than the server that the client is connected to.
It also protects the server check method against empty semver string.
fixes #1271 
=> Remove server version validation

async-nats/src/jetstream/context.rs, async-nats/src/jetstream/object_store/mod.rs
In line with the Go client: https://github.com/nats-io/nats.go/blob/370bc4fc4cac2de8d5dbbddbb98739f9cb2d7f8b/object.go#L283
=> Allow setting size limit for object storage buckets

async-nats/src/options.rs
Documentation didn't match implementation, resolves https://github.com/nats-io/nats.rs/issues/1275
=> Fix `subscription_capacity` documenttion default value

.github/workflows/test.yml, async-nats/Cargo.toml, async-nats/src/jetstream/context.rs, async-nats/src/lib.rs, async-nats/tests/jetstream_tests.rs
Being able to check if stream exist looking it up by subject was mentioned few times, recently here: https://github.com/vectordotdev/vector/pull/20834
=> Add stream_by_subject

deny.toml
As we allow BSD-3-Clause, there is no point in denying BSD-2-Clause in our dependencies, as it less restrictive.
=> Add BSD-2-Clause to allowed licenses

async-nats/src/header.rs
=> Create header name/value from String without reallocating

async-nats/src/jetstream/stream.rs
If someone does a serde serialize/deserialize roundtrip with jetstream::stream::Stream, it will result in error, as then `ConsumerLimits` will be `null`.
This should not happen in real-world scenarios, as server does not send nulls for those values, however its good to protect against those scenarios in case Go/nats-server changes its behaviour as some point in time.
closes #1293 
=> Fix serde Stream roundtrip

async-nats/src/jetstream/kv/mod.rs
This change fixes an issue when using a JetStream K/V store where a user is creating, deleting, and re-creating keys. If the last entry for a key is a `Operation::Delete` or `Operation::Purge`, the initial `self.update()` returns an error, causing the second part of the method to be exercised.
Prior to this change, if the entry was deleted or purged a `kv.put()` call is used which ignores the revision of that last entry. A single writer to the K/V store would succeed (as no other writers would write first) so no problem. However, if 2 writers attempt to create a key, then a second writer *could* call the `kv.put()` before the first writer calls `kv.put()`. This means that *both* writers get an `Ok(revision)` and can assume that they won the creation of the key.
When using a "distributed …
=> Fix KV create race after delete/purge

async-nats/Cargo.toml, async-nats/src/client.rs, async-nats/src/lib.rs
closes #1266 
An example real-world use case for this looks like this following:
https://github.com/rvolosatovs/wrpc/blob/85b043b84bd70fa2994cde8ced129d05b6739284/crates/transport-nats-next/src/lib.rs#L351-L412
This in an `AsyncWrite` implementation, which chunks bytes according to NATS payload limits and correctly handles polling and async wake up (using the `Publisher` introduced in this PR)
=> feat: implement `futures::Sink<PublishMessage>` on `async_nats::Client`

async-nats/src/jetstream/kv/mod.rs, async-nats/tests/kv_tests.rs
=> Add `seen_current` to kv

nats/src/jetstream/types.rs, nats/tests/jetstream.rs
Addendum to #1300 for the `nats` module.
This PR instructs serde to rename `sample_frequency` into `sample_freq` during de/serialization.
It also introduces a module for converting the `u8` into a `String`.
Finally, this PR adds a test in `nats/tests/jetstream.rs` that can be executed via `cargo test -- jetstream_consumer_configs_sample_frequency`, which checks that the stored config of the consumer now contains the correctly set field.
Removing the `rename = sample_freq` directive from the `ConsumerConfig` type causes this test to fail, so all seems to be correct.
=> nats: De/Ser using `sample_freq` instead of `sample_frequency`

async-nats/src/jetstream/kv/mod.rs, async-nats/src/jetstream/message.rs, async-nats/src/jetstream/object_store/mod.rs, async-nats/src/jetstream/stream.rs, async-nats/tests/jetstream_tests.rs, async-nats/tests/kv_tests.rs
Having separate types returned by `get_raw_message` and `direct_get` seems to be unnecessary complicatinon.
Also logic for transforming from received Message was not encapsulated.
=> Rework get_raw_message to return `StreamMessage`

async-nats/src/jetstream/consumer/pull.rs
Although those unwraps seem safe, it's still better not not have app panicking at all.
Even in case of those somehow failing, client will recover by itself on next iteration of the timer.
If Stream is dropped, we also shutdown the task, so dropped sender/receiver should not matter.
=> Remove unwrap from consumer

.config/nats.dic, async-nats/src/jetstream/context.rs, async-nats/src/jetstream/stream.rs, async-nats/tests/jetstream_tests.rs
This methods allows for getting the handler for `Stream` without calling
the server info API.
It can be useful when user wants to perform single operation on many
streams.
=> Add get stream no io

async-nats/CHANGELOG.md, async-nats/Cargo.toml
This release adds a useful `futures::Sink<PublishMessage>`, and ability to get `Stream` handle without IO call,
among other changes.
This release introduces `StramMessage`, which makes both `get_raw_message` and `direct_get` methods return the same type, allowing
for more easier interop between two.
* Rework get_raw_message to return `StreamMessage` by @Jarema in https://github.com/nats-io/nats.rs/pull/1292
* Add stream_by_subject by @Jarema in https://github.com/nats-io/nats.rs/pull/1287
* Add `seen_current` to kv by @Jarema in https://github.com/nats-io/nats.rs/pull/1304
* Add get stream no io by @Jarema in https://github.com/nats-io/nats.rs/pull/1306
* Add `futures::Sink<PublishMessage>` on `async_nats::Client` by @rvolosatovs in https://github.com/nats-io/nats.rs/pull/1267
* Create …
=> Release async-nats v0.36.0

async-nats/tests/jetstream_tests.rs
This commit removes one test on purpose, as there will be a follow up PR that will use much better mechanic of strict JSON deserializing that should land in the server very soon.
=> Fix tests for server JS API versioning

async-nats/src/jetstream/kv/mod.rs, async-nats/tests/kv_tests.rs
Until now, if underlying watcher for given consumer did not have any pending messages, it would indefinitely wait for the first one. This commit improves it by checking message pending count on initial consumer info, and returning `None` if there are no messages.
=> Improve kv::Watcher without messages

async-nats/src/connection.rs, async-nats/src/connector.rs, async-nats/src/lib.rs, async-nats/tests/client_tests.rs
Client statistics should could all bytes that are coming in and out of the client, not just part of messages.
=> Improve statistics

async-nats/CHANGELOG.md, async-nats/Cargo.toml
A smaller release containing stats and Watcher improvements.
* Add Client stats by @Jarema in https://github.com/nats-io/nats.rs/pull/1314
* Improve kv::Watcher without messages by @Jarema in https://github.com/nats-io/nats.rs/pull/1321
**Full Changelog**: https://github.com/nats-io/nats.rs/compare/async-nats/v0.36.0...async-nats/v0.37.0
=> Release async-nats v0.37.0

.config/nats.dic, async-nats/src/jetstream/stream.rs, async-nats/tests/jetstream_tests.rs
This is a draft solution that tries to find a sensible way to fetch subjects for from `stream info`, which returns subjects with pagination nested under info.state.
=> Add ability to fetch stream subjects

async-nats/src/client.rs, async-nats/tests/client_tests.rs
This is neccessary for ergonomic Orbit extensions to the `Client`.
=> Add getter for Client request timeout

async-nats/src/auth.rs, async-nats/tests/client_tests.rs
The signature received from the nkeys::KeyPair sign function is a `Vec<u8>` and the contents cannot be stored in a String.
This commit changes the type of the signature field in the Auth struct from a `Option<String>` to a `Option<Vec<u8>>`.
This allows for JWTs to be used and signed with the nonce in the custom auth callback.
=> Change Auth struct signature field to `Vec<u8>`

async-nats/src/service/mod.rs
fix bug: adding back prefix in service group creation
Currently, the prefix will be missing if we are creating group from group.
e.g.
```
let sg = service.group("level1");
sg.endpoint("endpoint1") ==> we can expect to see "level1.endpoint1"
let g2 = sg.group("level2:);
g2.endpoint("endpoint2") ==> now we will see "level2.endpoint2"
```
this patch is to fix and apply the prefix for the g2 endpoint such that the topic will become
`level1.level2.endpoint2`
=> fix bug: adding back prefix in service group creation

async-nats/src/client.rs, async-nats/src/lib.rs, async-nats/tests/client_tests.rs
Based on the proposal in #1325, implementing the functionality described in [this NATS doc](https://docs.nats.io/using-nats/developer/receiving/drain). 
I would love suggestions for further tests. I tried adding tests for more complex timing/corner cases but they all wound up looking like exactly like the tests I have here
=> Implement the "drain" feature for subscriptions and connections

.github/workflows/test.yml, async-nats/tests/client_tests.rs
As port 7777 is used by some tools, like Prometheus, it is easy to get into conflict.
Additionally, Github Actions Windows machines seem to run something on that port.
=> Change port for some tests

async-nats/CHANGELOG.md, async-nats/Cargo.toml
This release adds Websockets support, using `tokio-websocket` implementation.
Feature is behind a feature flag `websockets`, enabled by default.
* Change Auth struct signature field to `Vec<u8>` by @mnordstr in https://github.com/nats-io/nats.rs/pull/1337
* Add Websockets support by @Jarema in https://github.com/nats-io/nats.rs/pull/1330
* Add ability to fetch stream subjects by @Jarema in https://github.com/nats-io/nats.rs/pull/1329
* Add getter for Client request timeout by @Jarema in https://github.com/nats-io/nats.rs/pull/1338
* Implement the "drain" feature for subscriptions and connections by @jsudano in https://github.com/nats-io/nats.rs/pull/1332
* Fix adding back prefix in service group creation by @rexf in https://github.com/nats-io/nats.rs/pull/1339
* @mnordstr made their first …
=> Release async-nats/v0.38.0

async-nats/src/jetstream/consumer/mod.rs, async-nats/src/jetstream/consumer/pull.rs, async-nats/src/jetstream/consumer/push.rs, async-nats/tests/jetstream_tests.rs
Closes #1353.
This PR updates `async-nats`'s deserialization routine for `sample_freq` in consumers to account for a terminating '%', which is seen in the wild when managing NATS resources using Terraform / OpenTofu. 
The changed code is partially tested by the same test added in #1300, but currently does not contain a test for the new case.
I instead tested it against the setup outlined in #1353.
I'd like to add such a case, but I'm not sure how to do so, as Rust's type system forbids me from creating a consumer with `sample_freq` set to something ending in %.
=> async-nats: Support `sample_freq` values containing a %

async-nats/tests/jetstream_tests.rs
Followup from #1354 
Previously merged test accidentally tested pull consumer configs twice, neglecting to test push consumer configs as well.
=> async-nats: check push consumers in `sample_freq` de/serialisation test

.github/workflows/test.yml, async-nats/Cargo.toml, async-nats/src/connector.rs, async-nats/src/tls.rs, async-nats/tests/kv_tests.rs
This reduces the dependencies footprint in scenarios when `websockets` and `aws-lc-rs` are not used.
=> Improve transient dependencies

async-nats/src/jetstream/object_store/mod.rs, async-nats/tests/kv_tests.rs, async-nats/tests/object_store.rs
=> Allow updating Object Store metadata headers and metadata

.config/nats.dic, async-nats/src/jetstream/kv/mod.rs, async-nats/src/jetstream/stream.rs, async-nats/tests/jetstream_tests.rs
=> Add additional methods for getting raw messages from the stream

async-nats/src/jetstream/errors.rs
The current `Display` message for `jetstream::Error` is a little confusing. For example, this piece of code:
```rust
#[tokio::main]
async fn main() -> Result<(), async_nats::Error> {
let client = async_nats::connect("localhost:4222").await?;
let jetstream = async_nats::jetstream::new(client);
if let Err(err) = jetstream.get_object_store("nonexistent").await {
eprintln!("{}", err);
}
Ok(())
}
```
prints
```
failed to get Object Store: jetstream error: 404 (code stream not found, error code 10059)
```
After this change, the message is:
```
failed to get Object Store: jetstream error: stream not found (code 404, error code 10059)
```
=> Change `jetstream::Error`'s `Display` message

async-nats/src/jetstream/kv/mod.rs, async-nats/tests/kv_tests.rs
=> Add kv::watch_many functions

async-nats/src/jetstream/object_store/mod.rs, async-nats/tests/object_store.rs
When an object already exists in the object store, `ObjectStore::put` is supposed to purge it. Currently, this does not happen because the object name is erroneously double-encoded.
To reproduce:
```rust
#[tokio::main]
async fn main() -> Result<(), async_nats::Error> {
let client = async_nats::connect("localhost:4222").await?;
let jetstream = async_nats::jetstream::new(client);
let kv = jetstream
.create_object_store(async_nats::jetstream::object_store::Config {
bucket: "store".to_owned(),
..Default::default()
})
.await?;
let mut file = tokio::fs::File::open("foo").await?;
kv.put("file", &mut file).await?;
let mut file = tokio::fs::File::open("bar").await?;
kv.put("file", &mut file).await?;
Ok(())
}
```
```bash
echo foo >foo
echo bar >bar
cargo run
nats stream view OBJ_store
``` 
Output: …
=> Delete old objects when calling `ObjectStore::put`

async-nats/Cargo.toml, nats/src/kv.rs, nats/src/object_store.rs
No features were experimental, but some mentiones were still there for old client or had stale additional feature flag.
=> Remove stale experimental flags mentions

async-nats/CHANGELOG.md, async-nats/Cargo.toml
This release focuses on improvements and fixes for Object Store and KV.
* Add kv::watch_many functions by @Jarema in https://github.com/nats-io/nats.rs/pull/1364
* Add metadata and headers to Object Store by @Jarema in https://github.com/nats-io/nats.rs/pull/1349
* Allow updating Object Store metadata headers and metadata by @Jarema in https://github.com/nats-io/nats.rs/pull/1362
* Add additional methods for getting raw messages from the stream by @Jarema in https://github.com/nats-io/nats.rs/pull/1359
* Support `sample_freq` values containing a % by @bengsparks in https://github.com/nats-io/nats.rs/pull/1354
* Improve push consumers in `sample_freq` de/serialisation test by @bengsparks in https://github.com/nats-io/nats.rs/pull/1356
* Delete old objects when calling `ObjectStore::put` by …
=> Release async-nats/v0.39.0

.github/workflows/test.yml, async-nats/src/jetstream/kv/mod.rs, async-nats/src/jetstream/stream.rs, async-nats/tests/jetstream_tests.rs, async-nats/tests/kv_tests.rs
In PR #1321, we introduced a change that was stopping watcher if there were no keys when starting the watch.
This is undesired behaviour, as watcher should allow for endless watch, no matter if there are keys or not.
This PR sets `seen_current` bool instead.
fixes #1376 
=> Revert stopping watcher and set `seen_current` instead

.gitignore, async-nats/src/lib.rs
as the parsing of the strings goes through Url the output behavior is incorrect when the implicit defaults of `Url` are ignored.
for example `wss://nats-server.com:443` would previously lead to the client trying to connect to port `4222`, because `Url::port` returns `None` for this case.
=> fix(ServerAddr): align port() with `Url::port_or_known_default`

async-nats/CHANGELOG.md, async-nats/Cargo.toml
This release focuses on adding support for nats-server v2.11.
* Add pause consumer by @Jarema in https://github.com/nats-io/nats.rs/pull/1385
* Add per message ttl and delete markers support by @Jarema in https://github.com/nats-io/nats.rs/pull/1387
* Add Consumer Groups and Overflow support by @Jarema in https://github.com/nats-io/nats.rs/pull/1384
* Revert stopping watcher and set `seen_current` instead by @Jarema in https://github.com/nats-io/nats.rs/pull/1377
* Fix alignment of port() with `Url::port_or_known_default` by @steveej in https://github.com/nats-io/nats.rs/pull/1383
* Derive Clone for Key/Value store Config by @jephthia in https://github.com/nats-io/nats.rs/pull/1381
* Change docs for jetstream::consumer::Info by @danyi1212 in https://github.com/nats-io/nats.rs/pull/1386
* …
=> Release async-nats v0.40.0

async-nats/src/connector.rs
If the code using the client does not read events fast enough, it could lead to blocking the internals of the client.
This commit makes sure that all event sends will not block even if the channel is full.
=> Always use try_send on events channels to avoid potential blocks

async-nats/src/jetstream/consumer/pull.rs
Actually, info should fail after few tried, giving user feedback.
=> Revert endless retry on consumer info

async-nats/dependencies.md, deny.toml
As webpki-roots pulled in by `tokio-websockets` (our optional dependency) and it's certificate data is licensed under CDLA, it requires us to add an exception to the license check.
=> Add note about webpki-roots license

async-nats/CHANGELOG.md, async-nats/Cargo.toml
This release focuses on adding limit markers support to KV.
* Add more detailed tracing by @caspervonb in https://github.com/nats-io/nats.rs/pull/1393
* Add kv limit markers by @Jarema in https://github.com/nats-io/nats.rs/pull/1404
* Add create_or_update and update methods to KV by @Jarema in https://github.com/nats-io/nats.rs/pull/1407
* Always use try_send on events channels to avoid potential blocks by @Jarema in https://github.com/nats-io/nats.rs/pull/1391
* Revert endless retry on consumer info by @Jarema in https://github.com/nats-io/nats.rs/pull/1399
* Fix consumer info error handling by @Jarema in https://github.com/nats-io/nats.rs/pull/1400
* Handle no responders in Consumers and never giving up by @Jarema in https://github.com/nats-io/nats.rs/pull/1398
* Fix typo in …
=> Release async-nats/v0.41.0

async-nats/src/client.rs, async-nats/src/lib.rs, async-nats/tests/client_tests.rs
This allows others to extend the client.
It introduces first set of traits.
It introduces new `traits` module to avoid name conflicts.
=> Add client traits

async-nats/src/client.rs
Hi there!
While debugging a NATS-driven application we hit the "max message payload exceeded" error in the Rust client. It took a little re-reading to realize that the 2 numbers (that is, the `max_payload` limit and the `payload.len()` of the current message) were revered in the Rust error. This change swaps them 😄 
Thanks!
=> Fix the order of the max payload exceeded message numbers

async-nats/CHANGELOG.md, async-nats/Cargo.toml
This releases focuses on some fixes and addition of Client traits that allow for easier extension of the client.
* Fix getting account info on server < 2.11 by @Jarema in https://github.com/nats-io/nats.rs/pull/1413
* Add client traits by @Jarema in https://github.com/nats-io/nats.rs/pull/1411
* Fix object store getting empty or deleted object by @Jarema in https://github.com/nats-io/nats.rs/pull/1415
* Fix the order of the max payload exceeded message numbers by @fnichol in https://github.com/nats-io/nats.rs/pull/1416
* Fix fetching messages before polling for them by @Jarema in https://github.com/nats-io/nats.rs/pull/1418
**Full Changelog**: https://github.com/nats-io/nats.rs/compare/async-nats/v0.41.0...async-nats/v0.41.1
=> Release async-nats v0.42.0

async-nats/src/jetstream/consumer/mod.rs, async-nats/src/jetstream/consumer/pull.rs
This PR exposes the `get_info` method on consumer, just like it is for stream already.
=> Expose get_info for consumer

async-nats/src/connector.rs, async-nats/src/lib.rs
Added port and path to the URI used to open the WebSocket (ws or wss), to support connections through a reverse proxy.
Solves issue #1425
=> Add port/path support for WebSockets

async-nats/src/subject.rs
Quality of life improvement for those using bytes already for subject to avoid conversions that may possibly allocate when not required.
=> feat(async-nats): add TryFrom<Bytes> support for subject

.config/nats.dic, async-nats/Cargo.toml, async-nats/benches/jetstream.rs, async-nats/src/jetstream/context.rs, async-nats/src/jetstream/mod.rs, async-nats/tests/jetstream_tests.rs
Clients that are missing backpressure for async publishing of JetStream messages can negatively impac the NATS servers and clusters.
Rust client separates publish with ack, as two separate futures, which is fine and very flexible, but does not enforce any backpressure, or enable easier handling of it. That is especially relevant for users dropping `PublishAckFuture` and ignoring the `Ack` entirely.
This PR addresses this in two ways:
1. Error on `Context::publish` if the threshold for in-flight acks is reached
2. Spin a task that awaits for acks for `PubAckFuture` that were dropped.
1. A new background task was needed. This should be fine, as it idles if user does not drop acks.
2. Increased memory footprint of `Context`.
=> Add backpressure to publish

async-nats/src/jetstream/context.rs
=> Abort acker only when last context instance is dropped

async-nats/CHANGELOG.md, async-nats/Cargo.toml
A hotfix for a regression that was introduced with direct get builder that affected also KV.
* Fix direct get with nats-server 2.11 & improve testing against older servers by @Jarema in https://github.com/nats-io/nats.rs/pull/1458
* Properly handle acker cleanup by @Jarema in https://github.com/nats-io/nats.rs/pull/1460
**Full Changelog**: https://github.com/nats-io/nats.rs/compare/async-nats/v0.43.0...async-nats/v0.43.1
=> Release async-nats/v0.43.1

async-nats/Cargo.toml
The service API is stable for quite some time.
=> Enable service API by default

async-nats/CHANGELOG.md, async-nats/Cargo.toml
A release that focuses on reorganization of types and improvement of extension traits for [orbit](https://github.com/synadia-io/orbit.rs)
* Enable service API by default by @Jarema in https://github.com/nats-io/nats.rs/pull/1461
* Extend client traits by @Jarema in https://github.com/nats-io/nats.rs/pull/1456
* Reorganize `message` types by @Jarema in https://github.com/nats-io/nats.rs/pull/1462
**Full Changelog**: https://github.com/nats-io/nats.rs/compare/async-nats/v0.43.1...async-nats/v0.44.0
=> Release v0.44.0
