nats-io/nats.rs

- src/lib.rs
This presents a fix that allows the `with_handler` return value to not be captured but to still maintain interest and fire callbacks. Previously this code immediately unsubscribed interest in foo when the line completed and the temporary `Subscription` was dropped.
```rust
nc.subscribe("foo")?.with_handler(move |msg| {
println!("Received {}", &msg);  
Ok(())
}
```
Also `with_handler` now returns a `SubscriptionHandler` which only allows `close()` or `unsubscribe()` calls, so you can not iterate on these or call `with_handler()` twice.
Signed-off-by: Derek Collison <derek@nats.io>
> Fix for issue #2

- .github/workflows/clippy.yml
This is a configuration for running clippy via GitHub Actions
> Add clippy GitHub Action configuration

- CHANGELOG.md
- Cargo.toml
cc @derekcollison this will let folks play with TLS right away
> Cut version 0.3.1

- .github/ISSUE_TEMPLATE/blank_issue.md
- .github/ISSUE_TEMPLATE/bugs.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
Once we agree on the wording etc... I'm happy to repeat this for our other public repos
To see the effect of this, try opening an issue at https://github.com/rust-lang/rust
> Add GitHub issue templates to encourage high quality issues

- src/inbound.rs
- src/outbound.rs
This implements parity with https://github.com/nats-io/nats.go/issues/565
> Retry learned and configured servers with equal probability

- examples/nats-box/main.rs
I tried several versions of this, feels like it should be easier.
First attempt always called with_credentials() and wanted it to do right thing with empty creds.
Second attempt built up options, but when I tried top reassign with credentials complained because it was different types.
Signed-off-by: Derek Collison <derek@nats.io>
> Allow --creds flag

- src/outbound.rs
this brings the rust client more-or-less up to the go client's performance.
on my laptop, this gets us to 6.5m writes/s (before this is 2.8m/s due to heavy lock contention and the flusher constantly writing small buffers), with the go client doing 7.4m/s.
> Auto-tune flusher back-off

- src/asynk/client.rs
- src/asynk/connection.rs
- src/asynk/connector.rs
- src/asynk/message.rs
- src/asynk/proto.rs
- src/connect.rs
- src/headers.rs
- src/lib.rs
the doctest passes when used against a local recent server running the master branch of nats-server, but fails against demo.nats.io. @derekcollison the doctest is no_run for now until `demo.nats.io` uses our next release that includes header support.
> Initial headers implementation

- src/asynk/subscription.rs
- src/subscription.rs
Since `Subscription` is cloneable and `asynk::Subscription` isn't, `Subscription` would contain an `Arc<Mutex<asynk::Subscription>>` inside it.
A deadlock occurs if a `next()` operation acquires the mutex and then yields because there are no messages to receive. Then, a `drain()` operation would not be able to acquire the mutex so it would yield too without ever waking up the `next()` operation.
The solution is to make `asynk::Subscription` shareable across threads (by making its methods require `&self` rather than `&mut self`). Then we don't need the mutex at all and everything becomes much simpler. Really, this PR is more of a cleanup than a bugfix :)
Fixes #82
> Fix a deadlock when draining subscriptions

- CHANGELOG.md
- Cargo.toml
> Prepare v0.7.2 for release

- src/asynk/message.rs
This is the same function that exists on the sync part but on the async one
Fixes #96
> Add respond on asynk::Message

- src/asynk/connector.rs
- src/auth_utils.rs
- src/connect.rs
- src/lib.rs
- src/options.rs
- tests/connect.rs
This PR adds a new authentication method: `Options::with_nkey()`.
> Add NKey authentication

- .github/workflows/test.yml
- Cargo.toml
- src/asynk/connector.rs
This is just a test right now - I changed `async-tls` to `async-rustls`.
> Attempt to fix TLS

- .github/ISSUE_TEMPLATE/bugs.md
Corrects crate name in grep command.
> Correct crate name in issue template

- src/asynk/client.rs
- src/asynk/connector.rs
- src/options.rs
disconnect_callback
reconnect_callback
reconnect_delay_callback
max_reconnects
close_callback
[WIP]
I'm a bit confused about what max_reconnects is meant to be:
> /// Set the maximum number of reconnect attempts.
> /// If no servers remain that are under this threshold,
> /// all servers will still be attempted.
Isn't this conflicting, saying if no server remains under the max attempts, then connect anyway... ?
I'm not sure how to implement the close_callback for the drain/close situation because the client dispatch where we wait for op's does not seem to have "visibility" over the close.
> Implement missing options

- src/asynk/connection.rs
- src/lib.rs
- tests/drop.rs
> Shutdown when the last reference to Connection is dropped

- src/options.rs
This is the equivalent of `Options.UserJwt` in Go: https://pkg.go.dev/github.com/nats-io/nats.go#UserJWT
> Add Options::with_jwt()

- nats_test_server/Cargo.toml
> Cut new test server release

- nats_test_server/src/lib.rs
Being in blocking mode initially meant that a server with no clients at the end of a test would be stuck waiting for clients and wouldn't read the shutdown flag - meaning the test couldn't complete.
This makes the `TCPListener` always non-blocking.
> Make test server accept non-blocking

- Cargo.toml
- src/connector.rs
Fixes #122 
See https://github.com/nats-io/nats.rs/issues/122#issuecomment-757980590 for the explanation.
> Skip native certs that can't be loaded

- src/auth_utils.rs
- src/options.rs
> Add support for static creds parsing

- src/client.rs
Fixes https://github.com/nats-io/nats.rs/issues/182
> Reset client writer to None upon disconnection from server

- src/asynk.rs
- tests/drop.rs
This addresses the comments from https://github.com/nats-io/nats.rs/pull/209 and closes https://github.com/nats-io/nats.rs/issues/213.
> auto-close async subscriptions

- src/jetstream_types.rs
See https://github.com/nats-io/nats-architecture-and-design/issues/44
> Add domain field to `PubAck`

- src/jetstream.rs
- src/lib.rs
- src/options.rs
https://github.com/nats-io/nats-architecture-and-design/issues/52
> Allow setting a jetstream api prefix from a domain

- Cargo.toml
- src/jetstream.rs
- tests/configs/jetstream_account_not_enabled.conf
- tests/jetstream.rs
This takes some steps towards improving `JetStream` error handling.
- Box `jetstream::Error` into `io::Error`
- Adds error codes to `jetstream::Error` (generated from errors.json and edited a little bit)
> Improve error handling

- src/jetstream.rs
- tests/jetstream.rs
First step to get rid of Consumer as it is now.
> Move Consumer Management to JetStream

- src/jetstream.rs
- tests/jetstream.rs
PR to make API more consisten with Go client.
I also moved around fn's in `impl JetStream` to have them grouped, though git make the diff little confusing.
> Rename create_stream to add_stream

- src/client.rs
- src/message.rs
- src/options.rs
- tests/async_errors.rs
- tests/configs/perms.conf
Added in async error callback with defaults eprintln!
Made Message is_no_responders() public for normal use.
Signed-off-by: Derek Collison <derek@nats.io>
> Some additions..

- Cargo.toml
- src/auth_utils.rs
- src/client.rs
- src/header.rs
- src/jetstream.rs
- src/jetstream_kv.rs
- src/jetstream_push_subscription.rs
- src/jetstream_types.rs
- src/lib.rs
- src/message.rs
- tests/jetstream.rs
- tests/jetstream_kv.rs
Implements key-value store as per the ADR.
> Implement key-value store

- Cargo.toml
- src/jetstream.rs
- src/kv.rs
- src/lib.rs
- src/object_store.rs
- tests/jetstream_object.rs
- tests/kv.rs
- tests/object_store.rs
> Jarema/reorganize kv and object_store modules

- src/kv.rs
- tests/kv.rs
* add missing function to watch specific keys
* align API for watching over kv with Go client
> Add watch and rename watch to watch_all

- src/kv.rs
Always delete the store when one is created at demo.nats.io.
Resolves #293
> Harden kv doctests

- src/jetstream/mod.rs
> Change jetstream log level to debug

- src/jetstream/mod.rs
- src/jetstream/pull_subscription.rs
- cherry picked  commit from #311 
- reshuffled methods so docs shows the high-level ones first
- added missing docs for iterator
fixes #311
> Fix Pull Subscriber visibility

- src/client.rs
- src/proto.rs
- tests/drop.rs
Using workaround for now, as sync client is coming soon.
> Fixh push consumer hang on close

- src/kv.rs
Partially implements https://github.com/nats-io/nats-architecture-and-design/issues/94 (first bullet point)
> Adapt discard policy according to server version

- nats-experimental/Cargo.toml
- nats-experimental/src/lib.rs
35 seconds for 100 000 000
33 now.
> Do not use format in publish

- nats/src/object_store.rs
Fixes a minor clippy warning that would show up in CI
> Fix clippy warning

- async-nats/src/lib.rs
Let's hide what does not have to be public.
> Make some structs private and add some docs

- async-nats/src/lib.rs
> Only send reconnect event once

- .github/workflows/test.yml
- Cargo.toml
- async-nats/Cargo.toml
- async-nats/benches/core_nats.rs
- nats-server/Cargo.toml
- nats-server/src/lib.rs
- nats/Cargo.toml
- nats/benches/nats_bench.rs
A draft.
Pushed to see how GHA runs them.
> Add benchmarks

- .github/workflows/test.yml
- Includes cargo.toml in cache key.
- Restores the cache after checkout to prevent it wiping it.
> More workflow improvements

- async-nats/src/jetstream/consumer/pull.rs
Quick minor cleanup of internal batch stream message matching.
> Refactor batch matching

- async-nats/src/jetstream/consumer/pull.rs
Prior art in both std and our old nats implementation tends to lean towards nouns without a suffix.
> Rename `BatchIter` to `Batch`

- async-nats/src/jetstream/context.rs
- async-nats/tests/jetstream_tests.rs
> Make `Context::update_stream` consistent with other Context methods

- async-nats/src/jetstream/consumer/mod.rs
- async-nats/src/jetstream/consumer/push.rs
- async-nats/tests/jetstream_tests.rs
> Move push to its own module

- async-nats/src/jetstream/consumer/mod.rs
- async-nats/src/jetstream/context.rs
- async-nats/src/jetstream/stream.rs
> Rename StreamInfo to Info

- async-nats/src/jetstream/consumer/mod.rs
- async-nats/tests/jetstream_tests.rs
> Add Consumer::info and Consumer::cached_info

- async-nats/src/jetstream/consumer/pull.rs
- async-nats/src/jetstream/mod.rs
> Rename JetStreamMessage to Message

- async-nats/tests/jetstream_tests.rs
> Make ack tests safe against consumer state consistency

- Readme.md
- async-nats/CHANGELOG.md
- nats/CHANGELOG.md
> Release async-nats/v0.15.0 nats/v0.21.0

- async-nats/src/jetstream/consumer/mod.rs
- async-nats/src/jetstream/mod.rs
- async-nats/src/jetstream/stream.rs
> Fix broken docs links

- async-nats/src/jetstream/stream.rs
- async-nats/tests/jetstream_tests.rs
> Change `create_consumer` to return `Consumer`

- async-nats/src/jetstream/consumer/pull.rs
- async-nats/tests/jetstream_tests.rs
> Handle missing eror cases in Stream

- async-nats/src/client.rs
- async-nats/src/jetstream/consumer/pull.rs
- async-nats/src/jetstream/message.rs
> Fix docs links

- async-nats/src/header.rs
- async-nats/src/message.rs
> Add Message and Headers docs

- async-nats/examples/jetstream_pull.rs
- async-nats/src/jetstream/consumer/pull.rs
> Add more docs to Pull Consumer

- nats-server/src/lib.rs
> Remove trace and debug from nats-server wrapper

- async-nats/benches/core_nats.rs
Our higher number of messages in every sample was done due to considerations that smaller the sample, bigger the impact of tokio runtime spawn for every sample.
Turns out, this is negible. Reduced the sample sie one order of magnitude and results are very similar.
Going below 100 messages per sample starts to impact results significantly.
> Make benchmarks more lightweight

- async-nats/src/lib.rs
- async-nats/src/options.rs
- async-nats/tests/client_tests.rs
> Add no_echo option

- async-nats/src/jetstream/consumer/pull.rs
- async-nats/src/jetstream/consumer/push.rs
> Add Push Consumer stream docs

- async-nats/src/jetstream/account.rs
- async-nats/src/jetstream/consumer/mod.rs
- async-nats/src/jetstream/consumer/push.rs
- async-nats/src/jetstream/publish.rs
- async-nats/src/jetstream/stream.rs
- async-nats/src/message.rs
- async-nats/src/status.rs
> Fix license headers

- async-nats/src/lib.rs
> Fix slow connect in no-auth scenarios

- async-nats/src/jetstream/consumer/pull.rs
- async-nats/tests/jetstream_tests.rs
> Make Pull Consumer defaults consistent

- async-nats/src/jetstream/consumer/mod.rs
- async-nats/src/jetstream/consumer/pull.rs
- async-nats/src/jetstream/consumer/push.rs
- async-nats/src/jetstream/stream.rs
- async-nats/tests/jetstream_tests.rs
after merging #571 I will be able to test this directly.
> Add `ClusterInfo` and `PeerInfo`

- async-nats/Cargo.toml
- async-nats/examples/concurrent.rs
Copied from NATS-by-example.
Especially until that repo compiles those examples, its good to have them here.
> Add concurrent example

- async-nats/examples/jetstream_pull.rs
- async-nats/examples/json.rs
- async-nats/logs
> Improve JetStream example

- async-nats/src/connector.rs
- async-nats/src/lib.rs
- async-nats/src/tls.rs
- async-nats/tests/jwt.rs
Splits out connector into its own private module and handles authorization inline.
> Fix reconnect auth deadlock

- async-nats/CHANGELOG.md
- async-nats/src/options.rs
> Improve callback docs

- async-nats/src/jetstream/stream.rs
- async-nats/tests/jetstream_tests.rs
Adding missing bits and inconsistencies found while implementing Object Store.
> Add stream info and cached_info

- async-nats/src/connector.rs
- async-nats/src/jetstream/consumer/pull.rs
- async-nats/src/jetstream/message.rs
- async-nats/src/lib.rs
- nats/src/connector.rs
- nats/src/message.rs
- nats/src/options.rs
> Remove unnecesary events sender clone

- async-nats/src/client.rs
- async-nats/src/connection.rs
- async-nats/src/connector.rs
- async-nats/src/lib.rs
- async-nats/tests/client_tests.rs
> Add connection state watcher

- async-nats/CHANGELOG.md
- async-nats/Cargo.toml
> Release async-nats/v0.19.0

- async-nats/src/jetstream/consumer/pull.rs
- async-nats/src/jetstream/consumer/push.rs
- async-nats/src/status.rs
- async-nats/tests/jetstream_tests.rs
- nats/src/jetstream/types.rs
> Fix heartbeat typo

- async-nats/src/header.rs
> Add HeaderMap::is_empty

- async-nats/src/lib.rs
Client did not reset pending ping count on reconnect.
That caused potential mismatch and constant disconenct/reconnect on each PING sent.
fixes #648 
> Fix potential pending pings mismatch on reconnects

- async-nats/src/jetstream/context.rs
- async-nats/src/jetstream/kv/mod.rs
- async-nats/tests/kv_tests.rs
implements https://github.com/nats-io/nats-architecture-and-design/issues/137
> Add republish to KV

- async-nats/src/connector.rs
- async-nats/src/lib.rs
- async-nats/src/options.rs
- async-nats/tests/client_tests.rs
fixes #661 
Signed-off-by: Jarema <tomasz@nats.io>
> Add retry on initial connect

- async-nats/src/lib.rs
- async-nats/src/options.rs
> Replace println with tracing

- async-nats/src/options.rs
> Improve event logging

- async-nats/src/jetstream/object_store/mod.rs
> Improve object get example

- async-nats/CHANGELOG.md
- async-nats/Cargo.toml
> async-nats relase v0.22.0

- async-nats/src/jetstream/context.rs
as @stevelr pointed out, there is no way to reduce in-between flushes lag for new publish with `IntoFuture`.
Hence, until flushing is improved, I'm adding flush to acking.
> Flush on publish ack await

- .github/workflows/test.yml
- deny.toml
Setup cargo deny and add to CI workflow to resolve issue #698
> Setup cargo deny to check licenses

- async-nats/src/jetstream/object_store/mod.rs
- async-nats/tests/object_store.rs
> Fix object store watch to retrieve only new/changed values

- .github/workflows/test.yml
- async-nats/src/lib.rs
> Add docs lint

- async-nats/src/jetstream/object_store/mod.rs
- async-nats/tests/object_store.rs
> Add object store list

- async-nats/src/client.rs
- async-nats/src/jetstream/consumer/pull.rs
> Make publish error types consistent

- async-nats/src/jetstream/object_store/mod.rs
- async-nats/tests/object_store.rs
> Fix stack overflow in object store

- async-nats/src/header.rs
- async-nats/src/jetstream/consumer/pull.rs
- async-nats/src/jetstream/consumer/push.rs
- async-nats/src/jetstream/context.rs
- async-nats/src/jetstream/mod.rs
- async-nats/src/jetstream/object_store/mod.rs
- async-nats/src/jetstream/stream.rs
- async-nats/src/lib.rs
- async-nats/src/options.rs
- async-nats/tests/client_tests.rs
- async-nats/tests/jetstream_tests.rs
- async-nats/tests/kv_tests.rs
- nats/docs/migration-guide-0.17.0.md
- nats/nats_test_server/README.md
- nats/nats_test_server/src/lib.rs
- nats/src/asynk.rs
- nats/src/client.rs
- nats/src/jetstream/mod.rs
- nats/src/jetstream/pull_subscription.rs
- nats/src/jetstream/push_subscription.rs
- nats/src/jetstream/types.rs
- nats/src/kv.rs
- nats/src/object_store.rs
- nats/src/options.rs
- nats/src/secure_wipe.rs
- nats/src/subscription.rs
- nats/tests/drop.rs
- nats/tests/no_messages.rs
There are some minor spelling mistakes that have been corrected, this mostly is for documentation and logging.  But there are some changes to variable and function names.
> Fix various spelling mistakes

- async-nats/src/jetstream/stream.rs
- async-nats/tests/jetstream_tests.rs
Addresses https://github.com/nats-io/nats-architecture-and-design/issues/10
> Add deleted messages details to stream info

- nats/benches/nats_bench.rs
> Fix lint in nats bench

- async-nats/tests/jetstream_tests.rs
- nats/tests/drop.rs
> Remove printlns from tests

- nats/src/jetstream/mod.rs
> Change JetStream request timeout to 5 seconds

- async-nats/src/service/mod.rs
- async-nats/tests/service_tests.rs
> Make service::add private

- async-nats/src/header.rs
This PR introduces 2 changes:
1. As other clients allow to get first header value and order should be retained, Vec is used instead of HashSet
2. Some convinienve methods around getting HeaderValue were added
fixes #760
> Ordered and convenient HeaderValue

- .config/nats.dic
- async-nats/src/service/error.rs
- async-nats/src/service/mod.rs
- async-nats/tests/service_tests.rs
Those changes adopt all recent changes in Service API.
> Improve service API

- async-nats/CHANGELOG.md
- async-nats/Cargo.toml
> Release async-nats/v0.25.0

- async-nats/src/jetstream/consumer/mod.rs
> Fix cluster field serialization for consumer info

- async-nats/CHANGELOG.md
- async-nats/Cargo.toml
> Release async-nats/v0.25.1

- async-nats/src/client.rs
- async-nats/src/jetstream/stream.rs
- async-nats/tests/client_tests.rs
Retargets #753 to the into_future branch
> Make `client::request` return an `into_future` based builder

- async-nats/examples/kv.rs
> Add kv example

- async-nats/src/jetstream/consumer/push.rs
- async-nats/tests/jetstream_tests.rs
> Fix queue push consumer

- async-nats/src/connector.rs
> Setup tls only if required

- .github/workflows/test.yml
> Remove hosts config

- async-nats/CHANGELOG.md
- async-nats/Cargo.toml
> Release async-nats/v0.26.0

- nats/examples/nats-box/main.rs
> Fix lint error

- async-nats/src/connector.rs
- async-nats/src/lib.rs
- async-nats/tests/client_tests.rs
> Fix no error when auth not provided but required

- async-nats/src/jetstream/consumer/push.rs
The spawned task watching the consumer and recreating was never aborted when the consumer was dropped
> fix(consumers): Fixes duplicate consumer creation

- async-nats/src/jetstream/stream.rs
- async-nats/tests/jetstream_tests.rs
> Add consumers and consumer names methods

- async-nats/src/connection.rs
> Send PUB instead of HPUB if headers are set but empty

- async-nats/src/jetstream/context.rs
- async-nats/tests/jetstream_tests.rs
> Improve error for jetstream publish

- nats/CHANGELOG.md
- nats/Cargo.toml
> Release nats/v0.24.0

- async-nats/src/jetstream/consumer/mod.rs
- async-nats/src/jetstream/consumer/pull.rs
- async-nats/src/jetstream/consumer/push.rs
- async-nats/src/jetstream/stream.rs
- async-nats/tests/jetstream_tests.rs
Addresses https://github.com/nats-io/nats-architecture-and-design/issues/200
> Add metadata support

- async-nats/src/jetstream/stream.rs
Change `Stream` in `stream.rs` `Purge` to be a ref
> Make `Stream` a ref in `Purge`

- async-nats/Cargo.toml
- async-nats/src/connector.rs
- async-nats/src/lib.rs
- async-nats/src/options.rs
- async-nats/tests/client_tests.rs
> Add retaining server list order option & Fix reconnect burst on auth failure

- async-nats/src/connection.rs
Here are changes that were suggested in https://github.com/nats-io/nats.rs/issues/889#issue-1634670217.
> Remove collect to Vec in try_read_op

- async-nats/src/lib.rs
- async-nats/tests/client_tests.rs
> Make SubscribeError public

- async-nats/src/connection.rs
- async-nats/src/connector.rs
- async-nats/src/lib.rs
Here are changes that were suggested in https://github.com/nats-io/nats.rs/issues/889#issuecomment-1478574922.
> Remove unnecessary clone for publish payloads

- async-nats/src/jetstream/kv/mod.rs
- async-nats/tests/kv_tests.rs
> Add `watch_with_history` to KV store

- async-nats/src/jetstream/object_store/mod.rs
- async-nats/tests/object_store.rs
Looking into interoperability of clients, adding test coverage for ObjectInfo serialization/deserialization.
Supersedes https://github.com/nats-io/nats.rs/pull/870
> Fix serialization of `object_store::ObjectInfo` fields

- async-nats/src/lib.rs
Closes #931 
Partially resolves https://github.com/nats-io/nats.rs/issues/923
> Reset ping interval on incoming and outgoing messages

- .github/workflows/test.yml
Documentation formatting is only available in nightly at this time.
> Use nightly toolchain for formatting check

- async-nats/src/lib.rs
> Disconnect if pending pings is more than max pings

- async-nats/src/lib.rs
This type is just used internally to communicate with the internal connection handler and not publicly useful to anyone.
> Make `Command` private

- async-nats/src/lib.rs
> Make `client` module public

- async-nats/Cargo.toml
- async-nats/src/service/endpoint.rs
- async-nats/src/service/mod.rs
- async-nats/tests/service_tests.rs
This addresses https://github.com/nats-io/nats-architecture-and-design/issues/220
> Remove schema and api_url from Service API

- nats-server/Cargo.toml
- nats-server/src/lib.rs
> Update nats server wrapper deps

- nats-server/Cargo.toml
- nats-server/src/lib.rs
> Add backoff to server test

- async-nats/src/connector.rs
- async-nats/src/lib.rs
- async-nats/src/options.rs
- async-nats/tests/client_tests.rs
Closes https://github.com/nats-io/nats.rs/issues/581
> Add `reconnect_delay_callback` to `ConnectOptions`

- async-nats/src/header.rs
Closes https://github.com/nats-io/nats.rs/issues/941
> Disallow non-alphanumeric in `HeaderName::from_str`

- async-nats/tests/jetstream_tests.rs
> Fix flaky cluster test

- async-nats/src/auth.rs
- async-nats/src/connector.rs
- async-nats/src/lib.rs
- async-nats/src/options.rs
- async-nats/tests/client_tests.rs
- async-nats/tests/jetstream_tests.rs
- async-nats/tests/jwt_tests.rs
- async-nats/tests/nkey_tests.rs
- async-nats/tests/tls_tests.rs
> Allow multiple auth methods

- async-nats/tests/jetstream_tests.rs
> Add test for updating consumer

- async-nats/src/jetstream/mod.rs
Rephrased and added JetStream top-level documentation.
> Improve top level `jetstream` module documentation

- async-nats/src/jetstream/kv/mod.rs
Added module level description and a missing doc for `get`. Also some miscellaneous.
> Improve JetStream KV documentation

- .config/nats.dic
- async-nats/src/lib.rs
Added and rephrased some documentation.
> Improve top level crate documentation

- async-nats/src/jetstream/kv/mod.rs
- async-nats/src/lib.rs
> Add concrete errors to KV

- async-nats/src/tls.rs
- nats/src/connector.rs
Deprecated in https://github.com/rustls/rustls/pull/1345 release 0.21.4
> Switch from deprecated rustls method

- async-nats/src/jetstream/consumer/pull.rs
- async-nats/src/jetstream/consumer/push.rs
- async-nats/src/jetstream/context.rs
- async-nats/src/jetstream/kv/mod.rs
- async-nats/src/jetstream/stream.rs
> Refactor Errors names to be less redundant

- async-nats/src/jetstream/stream.rs
Closes https://github.com/nats-io/nats.rs/issues/1001
> Change `stream::Config::duplicate_window` to `Duration`

- async-nats/src/jetstream/context.rs
> Remove JetStream error from request

- async-nats/src/jetstream/kv/mod.rs
- async-nats/src/jetstream/stream.rs
> Make JetStream error consistent

- async-nats/src/connection.rs
> Fix unwrap from `HeaderName::from_str` call

- async-nats/src/jetstream/consumer/push.rs
Doesn't fix my problem but it's something I noticed. The sequence number gets reset below but not here
> Add missing sequence number reset

- async-nats/src/header.rs
> Fix header name range validation

- async-nats/src/jetstream/object_store/mod.rs
> Drop subscription on list done

- async-nats/src/jetstream/consumer/push.rs
- async-nats/tests/jetstream_tests.rs
> Improve push consumer handling when encountering slow consumers

- async-nats/src/jetstream/kv/mod.rs
- async-nats/tests/kv_tests.rs
> Fix kv purge with prefix

- async-nats/Cargo.toml
- async-nats/tests/jetstream_tests.rs
- nats-server/Cargo.toml
* Bumping only outdated dependencies for now (as listed on deps.rs)
* Removal of tracing logs from tests
> Bump dependencies & remove tracing from tests

- async-nats/src/jetstream/object_store/mod.rs
- async-nats/tests/object_store.rs
> Remove link from metadata update

- async-nats/benches/core_nats.rs
Makes the allocator work less during benchmarks, reducing allocation noise and other unwanted side-effects
> Remove some allocations from benchmarks

- async-nats/benches/core_nats.rs
Before merging new flush behavior, we need confidence how it affects whole core NATS and JetStream.
This PR improves the benches in general and adds request/response benchmark.
Follow up will add JetStream Publish and JetStream Consumers.
> Improve benchmarks

- async-nats/Cargo.toml
- async-nats/src/jetstream/object_store/mod.rs
- async-nats/src/service/mod.rs
- nats-server/Cargo.toml
- nats-server/src/lib.rs
Diff: https://github.com/casualjim/rs-nuid/compare/v0.4.1...v0.5.0
> Update nuid crate to 0.5

- async-nats/src/jetstream/object_store/mod.rs
- async-nats/tests/object_store.rs
> feat(ObjectStore): Add watch_with_history method

- async-nats/src/client.rs
- async-nats/src/jetstream/kv/mod.rs
- async-nats/src/jetstream/object_store/mod.rs
- async-nats/src/service/mod.rs
- nats-server/src/lib.rs
- nats/src/jetstream/push_subscription.rs
- nats/src/subscription.rs
Fix the new lint errors added in recent `clippy`.
> Fix clippy errors

- async-nats/src/jetstream/object_store/mod.rs
- async-nats/tests/object_store.rs
> Fix Object Store links structures

- .config/nats.dic
- async-nats/src/jetstream/object_store/mod.rs
- async-nats/tests/object_store.rs
> Add customization of Object Store chunk size

- async-nats/Cargo.toml
- async-nats/src/lib.rs
> Show features behind feature flags in docs

- .github/workflows/test.yml
> ci: bump Go to 1.20

- async-nats/src/jetstream/stream.rs
- async-nats/tests/jetstream_tests.rs
> Remove subject transform dest field

- async-nats/src/service/endpoint.rs
- async-nats/src/service/mod.rs
- async-nats/tests/service_tests.rs
> Add customizable queue groups to service API

- async-nats/Cargo.toml
> Enable 2.10 features by default

- .github/workflows/main.yml
> Bump go version in CI

- async-nats/src/client.rs
- async-nats/src/jetstream/consumer/pull.rs
- nats/nats_test_server/src/lib.rs
Those were added in a new clippy lints.
> Fix clippy warnings

- async-nats/src/options.rs
> Increase default channel capacity values

- async-nats/dependencies.md
- nats/dependencies.md
> Update dependencies.md files

- async-nats/benches/core_nats.rs
- async-nats/benches/jetstream.rs
- async-nats/examples/concurrent.rs
- async-nats/examples/jetstream_pull.rs
- async-nats/examples/jetstream_push.rs
- async-nats/examples/json.rs
- async-nats/examples/multiple_subs.rs
- async-nats/examples/sub.rs
- async-nats/src/client.rs
- async-nats/src/header.rs
- async-nats/src/jetstream/consumer/mod.rs
- async-nats/src/jetstream/consumer/pull.rs
- async-nats/src/jetstream/consumer/push.rs
- async-nats/src/jetstream/context.rs
- async-nats/src/jetstream/kv/mod.rs
- async-nats/src/jetstream/message.rs
- async-nats/src/jetstream/mod.rs
- async-nats/src/jetstream/object_store/mod.rs
- async-nats/src/jetstream/stream.rs
- async-nats/src/lib.rs
- async-nats/src/service/mod.rs
- async-nats/src/subject.rs
- async-nats/tests/client_tests.rs
- async-nats/tests/compatibility.rs
- async-nats/tests/jetstream_tests.rs
- async-nats/tests/jwt_tests.rs
- async-nats/tests/kv_tests.rs
- async-nats/tests/nkey_tests.rs
- async-nats/tests/service_tests.rs
- async-nats/tests/tls_tests.rs
> Pass subject at call sites bound to an AsSubject trait

- async-nats/src/service/mod.rs
- async-nats/tests/compatibility.rs
> Implement service cross compatibility tests

- async-nats/src/jetstream/context.rs
- async-nats/src/jetstream/kv/mod.rs
> Simplify compression for kv

- async-nats/Cargo.toml
Tracking https://github.com/rustls/rustls/pull/1525
> Bump ring crate to v0.17

- async-nats/Cargo.toml
- async-nats/src/service/endpoint.rs
- async-nats/src/service/mod.rs
- async-nats/tests/service_tests.rs
After recent changes in main, some schema validations are failing if defaut values are provided.
fixes #1149 
fixes #1148 
> Fix service defaults

- async-nats/src/lib.rs
> Add jetstream, kv, object store and service to top level docs examples

- async-nats/src/service/mod.rs
This addresses https://github.com/nats-io/nats.rs/issues/1138
> Changed `self` to a borrow in `Request::respond()`

- async-nats/tests/service_tests.rs
> Fix linter error in service test

- async-nats/src/jetstream/kv/mod.rs
- async-nats/tests/kv_tests.rs
> Add `create` function to kv store

- async-nats/benches/jetstream.rs
> Fix benchmark linter error

- async-nats/tests/kv_tests.rs
> Fix flaky cross account kv test

- async-nats/tests/kv_tests.rs
> Fix flaky kv test

- async-nats/src/lib.rs
Quality-of-life improvement for `connect()` function. With this changes it's straightforward to pass `Vec<String>` or `[&str]` directly into `connect()` function.
This is useful when passing list of NATS servers directly from configuration file or command-line argument.
> Add `ToServerAddrs` impl for array/vector of strings

- async-nats/src/jetstream/message.rs
- nats/src/jetstream/types.rs
- nats/src/lib.rs
> Updates message metadata and add sync client notice

- .github/workflows/test.yml
- async-nats/src/jetstream/context.rs
- async-nats/tests/client_tests.rs
> Add features check

- async-nats/src/jetstream/context.rs
- async-nats/src/jetstream/kv/mod.rs
- async-nats/src/jetstream/object_store/mod.rs
- async-nats/src/jetstream/stream.rs
- async-nats/tests/jetstream_tests.rs
> Add placement

- async-nats/tests/jetstream_tests.rs
> Change test from fetch to batch to debug flaky runs

- .github/workflows/main.yml
> Bump go version in benchmarks

- async-nats/src/jetstream/context.rs
> Fix get_stream_no_info docs

- async-nats/src/jetstream/stream.rs
> Fix typos in examples

- async-nats/tests/configs/docker/Dockerfile
> Bump rust version for cross-compatibility tests

- README.md
> Add orbit link

- async-nats/src/jetstream/object_store/mod.rs
- async-nats/tests/object_store.rs
> Add metadata and headers to Object Store

- async-nats/src/connection.rs
- async-nats/src/jetstream/consumer/pull.rs
- async-nats/src/lib.rs
- nats-server/src/lib.rs
> Fix linter warnings

- .github/workflows/main.yml
> Bump CI artifact upload action

- async-nats/src/jetstream/consumer/mod.rs
Clarifying the meaning of some fields of the consumer Info struct
Following discussion on NATS Slack community
https://natsio.slack.com/archives/CM3T6T7JQ/p1742503439496689
> Change docs for jetstream::consumer::Info

- async-nats/Cargo.toml
- async-nats/src/jetstream/consumer/mod.rs
- async-nats/src/jetstream/consumer/pull.rs
- async-nats/src/jetstream/consumer/push.rs
- async-nats/src/jetstream/stream.rs
- async-nats/tests/jetstream_tests.rs
> Add pause consumer

- .config/nats.dic
- async-nats/src/header.rs
- async-nats/src/jetstream/context.rs
- async-nats/src/jetstream/stream.rs
- async-nats/tests/jetstream_tests.rs
> Add per message ttl and delete markers support

- async-nats/src/jetstream/consumer/mod.rs
- async-nats/src/jetstream/consumer/pull.rs
- async-nats/src/jetstream/consumer/push.rs
- async-nats/tests/jetstream_tests.rs
> Hide consumer overflow behind feature flag

- async-nats/src/jetstream/account.rs
- async-nats/src/jetstream/context.rs
- async-nats/src/jetstream/kv/mod.rs
- async-nats/tests/jetstream_tests.rs
- async-nats/tests/kv_tests.rs
Addresses https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-48.md
> Add kv limit markers

- .github/workflows/test.yml
- async-nats/src/jetstream/context.rs
- async-nats/tests/kv_tests.rs
> Add create_or_update and update methods to KV

- async-nats/src/auth_utils.rs
- async-nats/src/connection.rs
- async-nats/src/error.rs
- async-nats/src/jetstream/account.rs
- async-nats/src/jetstream/consumer/pull.rs
- async-nats/src/jetstream/consumer/push.rs
- async-nats/src/jetstream/context.rs
- async-nats/src/jetstream/message.rs
- async-nats/src/jetstream/object_store/mod.rs
- async-nats/src/jetstream/stream.rs
- async-nats/src/service/endpoint.rs
- async-nats/src/tls.rs
> Fix getting account info on server < 2.11

- async-nats/src/jetstream/object_store/mod.rs
- async-nats/tests/object_store.rs
> Fix object store getting empty or deleted object

- async-nats/examples/sync_context.rs
- async-nats/src/connector.rs
- async-nats/src/error.rs
- async-nats/src/jetstream/context.rs
- async-nats/src/jetstream/kv/mod.rs
- async-nats/src/jetstream/message.rs
- async-nats/src/jetstream/object_store/mod.rs
- async-nats/src/jetstream/stream.rs
- async-nats/src/lib.rs
- async-nats/src/service/mod.rs
- async-nats/tests/client_tests.rs
- async-nats/tests/jetstream_tests.rs
- async-nats/tests/object_store.rs
- async-nats/tests/service_tests.rs
> Fix linter issues

- async-nats/tests/jetstream_tests.rs
> Add test to confirm user can promote mirror to a stream

- async-nats/Cargo.toml
- async-nats/src/jetstream/consumer/mod.rs
- async-nats/src/jetstream/consumer/pull.rs
- async-nats/tests/jetstream_tests.rs
> Add prioritized PriorityPolicy

- async-nats/src/jetstream/errors.rs
> Add missing errors types

- async-nats/CHANGELOG.md
- async-nats/Cargo.toml
* Add missing errors types by @Jarema in https://github.com/nats-io/nats.rs/pull/1464
**Full Changelog**: https://github.com/nats-io/nats.rs/compare/async-nats/v0.44.0...async-nats/v0.44.1
> Release v0.44.1

- async-nats/src/jetstream/context.rs
This PR adds a new `send_request` method to the JetStream `Context` that enables sending JetStream API requests without waiting for responses.
Currently, JetStream Context only provides a `request` method that waits for a single response. However, some JetStream operations (like the new batch get operations from ADR-31) return multiple responses as a stream. To support these patterns, we need a way to:
1. Send a JetStream API request with the proper prefix
2. Allow the caller to manage their own subscription for responses
3. Support custom response handling patterns
- Added `pub async fn send_request<S: ToSubject>(&self, subject: S, request: crate::client::Request) -> Result<(), crate::PublishError>`
- The method automatically prefixes the subject with the JetStream API prefix
- Returns …
> Add send_request method to JetStream Context
